/* =========================================================================
   Encuesta_APS — Catálogos oficiales de SISPRO
   -------------------------------------------------------------------------
   GENERADO por bd/sispro/gen_catalogos_sispro.js a partir de las tablas de
   referencia públicas de SISPRO (bd/sispro/tablas). No editar a mano.

     CAT_PAIS            249 países      — tabla Pais (ítem 65, variable 9)
     CAT_OCUPACION_CIUO  451 ocupaciones — tabla SGDCIUO (ítem 73, variable 18)
     CAT_EAPB            91 entidades   — tabla SGDCodigoEAPB (ítem 76, variable 21)

   `valor` es lo que guarda la ficha y `sispro` lo que se reporta en el
   archivo plano APS124CCFP. Coinciden salvo en el país: la ficha guarda el
   código ISO de dos letras (llave de cat.pais) y el reporte el numérico.
   ========================================================================= */

'use strict';

const CAT_PAIS = [
  { valor: "CO", etiqueta: "Colombia", sispro: "170" },
  { valor: "VE", etiqueta: "Venezuela", sispro: "862" },
  { valor: "AF", etiqueta: "Afganistán", sispro: "004" },
  { valor: "AX", etiqueta: "Aland", sispro: "248" },
  { valor: "AL", etiqueta: "Albania", sispro: "008" },
  { valor: "DE", etiqueta: "Alemania", sispro: "276" },
  { valor: "AD", etiqueta: "Andorra", sispro: "020" },
  { valor: "AO", etiqueta: "Angola", sispro: "024" },
  { valor: "AI", etiqueta: "Anguila", sispro: "660" },
  { valor: "AQ", etiqueta: "Antártida", sispro: "010" },
  { valor: "AG", etiqueta: "Antigua y Barbuda", sispro: "028" },
  { valor: "SA", etiqueta: "Arabia Saudita", sispro: "682" },
  { valor: "DZ", etiqueta: "Argelia", sispro: "012" },
  { valor: "AR", etiqueta: "Argentina", sispro: "032" },
  { valor: "AM", etiqueta: "Armenia", sispro: "051" },
  { valor: "AW", etiqueta: "Aruba", sispro: "533" },
  { valor: "AU", etiqueta: "Australia", sispro: "036" },
  { valor: "AT", etiqueta: "Austria", sispro: "040" },
  { valor: "AZ", etiqueta: "Azerbaiyán", sispro: "031" },
  { valor: "BS", etiqueta: "Bahamas", sispro: "044" },
  { valor: "BD", etiqueta: "Bangladés", sispro: "050" },
  { valor: "BB", etiqueta: "Barbados", sispro: "052" },
  { valor: "BH", etiqueta: "Baréin", sispro: "048" },
  { valor: "BE", etiqueta: "Bélgica", sispro: "056" },
  { valor: "BZ", etiqueta: "Belice", sispro: "084" },
  { valor: "BJ", etiqueta: "Benin", sispro: "204" },
  { valor: "BM", etiqueta: "Bermuda", sispro: "060" },
  { valor: "BY", etiqueta: "Bielorrusia", sispro: "112" },
  { valor: "BO", etiqueta: "Bolivia", sispro: "068" },
  { valor: "BQ", etiqueta: "Bonaire, San Eustaquio y Saba", sispro: "535" },
  { valor: "BA", etiqueta: "Bosnia-Herzegovina", sispro: "070" },
  { valor: "BW", etiqueta: "Botsuana", sispro: "072" },
  { valor: "BR", etiqueta: "Brazil", sispro: "076" },
  { valor: "BN", etiqueta: "Brunéi", sispro: "096" },
  { valor: "BG", etiqueta: "Bulgaria", sispro: "100" },
  { valor: "BF", etiqueta: "Burkina Faso", sispro: "854" },
  { valor: "BI", etiqueta: "Burundi", sispro: "108" },
  { valor: "BT", etiqueta: "Bután", sispro: "064" },
  { valor: "CV", etiqueta: "Cabo Verde", sispro: "132" },
  { valor: "KH", etiqueta: "Camboya", sispro: "116" },
  { valor: "CM", etiqueta: "Camerún", sispro: "120" },
  { valor: "CA", etiqueta: "Canadá", sispro: "124" },
  { valor: "QA", etiqueta: "Catar", sispro: "634" },
  { valor: "TD", etiqueta: "Chad", sispro: "148" },
  { valor: "CL", etiqueta: "Chile", sispro: "152" },
  { valor: "CN", etiqueta: "China", sispro: "156" },
  { valor: "CY", etiqueta: "Chipre", sispro: "196" },
  { valor: "KM", etiqueta: "Comoras", sispro: "174" },
  { valor: "CG", etiqueta: "Congo", sispro: "178" },
  { valor: "KP", etiqueta: "Corea del Norte", sispro: "408" },
  { valor: "KR", etiqueta: "Corea del Sur", sispro: "410" },
  { valor: "CI", etiqueta: "Costa de Marfil", sispro: "384" },
  { valor: "CR", etiqueta: "Costa Rica", sispro: "188" },
  { valor: "HR", etiqueta: "Croacia", sispro: "191" },
  { valor: "CU", etiqueta: "Cuba", sispro: "192" },
  { valor: "CW", etiqueta: "Curazao", sispro: "531" },
  { valor: "DK", etiqueta: "Dinamarca", sispro: "208" },
  { valor: "DM", etiqueta: "Dominica", sispro: "212" },
  { valor: "EC", etiqueta: "Ecuador", sispro: "218" },
  { valor: "EG", etiqueta: "Egipto", sispro: "818" },
  { valor: "SV", etiqueta: "El Salvador", sispro: "222" },
  { valor: "AE", etiqueta: "Emiratos Árabes Unidos", sispro: "784" },
  { valor: "ER", etiqueta: "Eritrea", sispro: "232" },
  { valor: "SK", etiqueta: "Eslovaquia", sispro: "703" },
  { valor: "SI", etiqueta: "Eslovenia", sispro: "705" },
  { valor: "ES", etiqueta: "España", sispro: "724" },
  { valor: "US", etiqueta: "Estados Unidos", sispro: "840" },
  { valor: "EE", etiqueta: "Estonia", sispro: "233" },
  { valor: "ET", etiqueta: "Etiopia", sispro: "231" },
  { valor: "PH", etiqueta: "Filipinas", sispro: "608" },
  { valor: "FI", etiqueta: "Finlandia", sispro: "246" },
  { valor: "FJ", etiqueta: "Fiyi", sispro: "242" },
  { valor: "FR", etiqueta: "Francia", sispro: "250" },
  { valor: "GA", etiqueta: "Gabon", sispro: "266" },
  { valor: "GM", etiqueta: "Gambia", sispro: "270" },
  { valor: "GE", etiqueta: "Georgia", sispro: "268" },
  { valor: "GH", etiqueta: "Ghana", sispro: "288" },
  { valor: "GI", etiqueta: "Gibraltar", sispro: "292" },
  { valor: "GD", etiqueta: "Granada", sispro: "308" },
  { valor: "GR", etiqueta: "Grecia", sispro: "300" },
  { valor: "GL", etiqueta: "Groenlandia", sispro: "304" },
  { valor: "GP", etiqueta: "Guadaluoe", sispro: "312" },
  { valor: "GU", etiqueta: "Guam", sispro: "316" },
  { valor: "GT", etiqueta: "Guatemala", sispro: "320" },
  { valor: "GF", etiqueta: "Guayana Francesa", sispro: "254" },
  { valor: "GG", etiqueta: "Guernsey", sispro: "831" },
  { valor: "GN", etiqueta: "Guinea", sispro: "324" },
  { valor: "GQ", etiqueta: "Guinea Ecuatorial", sispro: "226" },
  { valor: "GW", etiqueta: "Guinea-Bisáu", sispro: "624" },
  { valor: "GY", etiqueta: "Guyana", sispro: "328" },
  { valor: "HT", etiqueta: "Haiti", sispro: "332" },
  { valor: "HN", etiqueta: "Honduras", sispro: "340" },
  { valor: "HK", etiqueta: "Hong Kong", sispro: "344" },
  { valor: "HU", etiqueta: "Hungría", sispro: "348" },
  { valor: "IN", etiqueta: "India", sispro: "356" },
  { valor: "ID", etiqueta: "Indonesia", sispro: "360" },
  { valor: "IR", etiqueta: "Irán", sispro: "364" },
  { valor: "IQ", etiqueta: "Iraq", sispro: "368" },
  { valor: "IE", etiqueta: "Irlanda", sispro: "372" },
  { valor: "BV", etiqueta: "Isla Bouvet", sispro: "074" },
  { valor: "IM", etiqueta: "Isla de Man", sispro: "833" },
  { valor: "CX", etiqueta: "Isla de Navidad", sispro: "162" },
  { valor: "HM", etiqueta: "Isla Heard y Mcdonald", sispro: "334" },
  { valor: "NF", etiqueta: "Isla Norfolk", sispro: "574" },
  { valor: "IS", etiqueta: "Islandia", sispro: "352" },
  { valor: "KY", etiqueta: "Islas Caimán", sispro: "136" },
  { valor: "CC", etiqueta: "Islas Cocos", sispro: "166" },
  { valor: "CK", etiqueta: "Islas Cook", sispro: "184" },
  { valor: "FO", etiqueta: "Islas Feroe", sispro: "234" },
  { valor: "GS", etiqueta: "Islas Georgias del Sur y Sandwich del Sur", sispro: "239" },
  { valor: "FK", etiqueta: "Islas Malvinas", sispro: "238" },
  { valor: "MP", etiqueta: "Islas Marianas del Norte", sispro: "580" },
  { valor: "MH", etiqueta: "Islas Marshall", sispro: "584" },
  { valor: "SB", etiqueta: "Islas Solomon", sispro: "090" },
  { valor: "TC", etiqueta: "Islas Turcas y Caicos", sispro: "796" },
  { valor: "UM", etiqueta: "Islas Ultramarinas Menores de Estados Unidos", sispro: "581" },
  { valor: "VG", etiqueta: "Islas Vírgenes Británicas", sispro: "092" },
  { valor: "VI", etiqueta: "Islas Vírgenes de los Estados Unidos", sispro: "850" },
  { valor: "IL", etiqueta: "Israel", sispro: "376" },
  { valor: "IT", etiqueta: "Italia", sispro: "380" },
  { valor: "JM", etiqueta: "Jamaica", sispro: "388" },
  { valor: "JP", etiqueta: "Japón", sispro: "392" },
  { valor: "JE", etiqueta: "Jersey", sispro: "832" },
  { valor: "JO", etiqueta: "Jordania", sispro: "400" },
  { valor: "KZ", etiqueta: "Kazajistán", sispro: "398" },
  { valor: "KE", etiqueta: "Kenya", sispro: "404" },
  { valor: "KG", etiqueta: "Kirguistán", sispro: "417" },
  { valor: "KI", etiqueta: "Kiribati", sispro: "296" },
  { valor: "KW", etiqueta: "Kuwait", sispro: "414" },
  { valor: "LA", etiqueta: "Laos", sispro: "418" },
  { valor: "LS", etiqueta: "Lesoto", sispro: "426" },
  { valor: "LV", etiqueta: "Letonia", sispro: "428" },
  { valor: "LB", etiqueta: "Líbano", sispro: "422" },
  { valor: "LR", etiqueta: "Liberia", sispro: "430" },
  { valor: "LY", etiqueta: "Libia", sispro: "434" },
  { valor: "LI", etiqueta: "Liechtenstein", sispro: "438" },
  { valor: "LT", etiqueta: "Lituania", sispro: "440" },
  { valor: "LU", etiqueta: "Luxemburgo", sispro: "442" },
  { valor: "MO", etiqueta: "Macao", sispro: "446" },
  { valor: "MK", etiqueta: "Macedonia", sispro: "807" },
  { valor: "MG", etiqueta: "Madagascar", sispro: "450" },
  { valor: "MY", etiqueta: "Malasia", sispro: "458" },
  { valor: "MW", etiqueta: "Malaui", sispro: "454" },
  { valor: "MV", etiqueta: "Maldivas", sispro: "462" },
  { valor: "ML", etiqueta: "Mali", sispro: "466" },
  { valor: "MT", etiqueta: "Malta", sispro: "470" },
  { valor: "MA", etiqueta: "Marruecos", sispro: "504" },
  { valor: "MQ", etiqueta: "Martinica", sispro: "474" },
  { valor: "MU", etiqueta: "Mauricio", sispro: "480" },
  { valor: "MR", etiqueta: "Mauritania", sispro: "478" },
  { valor: "YT", etiqueta: "Mayotte", sispro: "175" },
  { valor: "MX", etiqueta: "México", sispro: "484" },
  { valor: "FM", etiqueta: "Micronesia", sispro: "583" },
  { valor: "MD", etiqueta: "Moldavia", sispro: "498" },
  { valor: "MC", etiqueta: "Mónaco", sispro: "492" },
  { valor: "MN", etiqueta: "Mongolia", sispro: "496" },
  { valor: "ME", etiqueta: "Montenegro", sispro: "499" },
  { valor: "MS", etiqueta: "Montserrat", sispro: "500" },
  { valor: "MZ", etiqueta: "Mozambique", sispro: "508" },
  { valor: "MM", etiqueta: "Myanmar (Former Burma)", sispro: "104" },
  { valor: "NA", etiqueta: "Namibia", sispro: "516" },
  { valor: "NR", etiqueta: "Nauru", sispro: "520" },
  { valor: "NP", etiqueta: "Nepal", sispro: "524" },
  { valor: "NI", etiqueta: "Nicaragua", sispro: "558" },
  { valor: "NE", etiqueta: "Niger", sispro: "562" },
  { valor: "NG", etiqueta: "Nigeria", sispro: "566" },
  { valor: "NU", etiqueta: "Niue", sispro: "570" },
  { valor: "NO", etiqueta: "Noruega", sispro: "578" },
  { valor: "NC", etiqueta: "Nueva Caledonia", sispro: "540" },
  { valor: "NZ", etiqueta: "Nueva Zelanda", sispro: "554" },
  { valor: "OM", etiqueta: "Omán", sispro: "512" },
  { valor: "NL", etiqueta: "Países Bajos", sispro: "528" },
  { valor: "PW", etiqueta: "Palaos", sispro: "585" },
  { valor: "PS", etiqueta: "Palestina", sispro: "275" },
  { valor: "PA", etiqueta: "Panamá", sispro: "591" },
  { valor: "PG", etiqueta: "Papua Nueva Guinea", sispro: "598" },
  { valor: "PK", etiqueta: "Paquistan", sispro: "586" },
  { valor: "PY", etiqueta: "Paraguay", sispro: "600" },
  { valor: "PE", etiqueta: "Perú", sispro: "604" },
  { valor: "PN", etiqueta: "Pitcairn", sispro: "612" },
  { valor: "PF", etiqueta: "Polinesia Francesa", sispro: "258" },
  { valor: "PL", etiqueta: "Polonia", sispro: "616" },
  { valor: "PT", etiqueta: "Portugal", sispro: "620" },
  { valor: "PR", etiqueta: "Puerto Rico", sispro: "630" },
  { valor: "GB", etiqueta: "Reino Unido", sispro: "826" },
  { valor: "CF", etiqueta: "República Centroafricana", sispro: "140" },
  { valor: "CZ", etiqueta: "República Checa", sispro: "203" },
  { valor: "CD", etiqueta: "República Democrática del Congo", sispro: "180" },
  { valor: "DO", etiqueta: "República Dominicana", sispro: "214" },
  { valor: "RE", etiqueta: "Reunion", sispro: "638" },
  { valor: "RW", etiqueta: "Ruanda", sispro: "646" },
  { valor: "RO", etiqueta: "Rumania", sispro: "642" },
  { valor: "RU", etiqueta: "Rusia", sispro: "643" },
  { valor: "EH", etiqueta: "Sahara Occidental", sispro: "732" },
  { valor: "WS", etiqueta: "Samoa", sispro: "882" },
  { valor: "AS", etiqueta: "Samoa Americana", sispro: "016" },
  { valor: "BL", etiqueta: "San Bartolomé", sispro: "652" },
  { valor: "KN", etiqueta: "San Cristóbal y Nieves", sispro: "659" },
  { valor: "SM", etiqueta: "San Marino", sispro: "674" },
  { valor: "MF", etiqueta: "San Martín (parte Francesa)", sispro: "663" },
  { valor: "SX", etiqueta: "San Martín (parte Holandesa)", sispro: "534" },
  { valor: "PM", etiqueta: "San Pedro y Miquelon", sispro: "666" },
  { valor: "VC", etiqueta: "San Vicente y las Granadinas", sispro: "670" },
  { valor: "SH", etiqueta: "Santa Helena, Ascensión y Tristán de Acuña", sispro: "654" },
  { valor: "LC", etiqueta: "Santa Lucia", sispro: "662" },
  { valor: "VA", etiqueta: "Santa Sede", sispro: "336" },
  { valor: "ST", etiqueta: "Santo Tome y Principe", sispro: "678" },
  { valor: "SN", etiqueta: "Senegal", sispro: "686" },
  { valor: "RS", etiqueta: "Serbia", sispro: "688" },
  { valor: "SC", etiqueta: "Seychelles", sispro: "690" },
  { valor: "SL", etiqueta: "Sierra Leona", sispro: "694" },
  { valor: "SG", etiqueta: "Singapur", sispro: "702" },
  { valor: "SY", etiqueta: "Siria", sispro: "760" },
  { valor: "SO", etiqueta: "Somalia", sispro: "706" },
  { valor: "LK", etiqueta: "Sri Lanka", sispro: "144" },
  { valor: "SZ", etiqueta: "Suazilandia", sispro: "748" },
  { valor: "ZA", etiqueta: "Sudáfrica", sispro: "710" },
  { valor: "SD", etiqueta: "Sudán", sispro: "729" },
  { valor: "SS", etiqueta: "Sudán del Sur", sispro: "728" },
  { valor: "SE", etiqueta: "Suecia", sispro: "752" },
  { valor: "CH", etiqueta: "Suiza", sispro: "756" },
  { valor: "SR", etiqueta: "Surinam", sispro: "740" },
  { valor: "SJ", etiqueta: "Svalbard y Jan Mayen", sispro: "744" },
  { valor: "TH", etiqueta: "Tailandia", sispro: "764" },
  { valor: "TW", etiqueta: "Taiwan", sispro: "158" },
  { valor: "TZ", etiqueta: "Tanzania", sispro: "834" },
  { valor: "TJ", etiqueta: "Tayikistán", sispro: "762" },
  { valor: "IO", etiqueta: "Territorio Británico del Océano Índico", sispro: "086" },
  { valor: "TF", etiqueta: "Tierras Australes y Antárticas Francesas", sispro: "260" },
  { valor: "TL", etiqueta: "Timor Oriental", sispro: "626" },
  { valor: "TG", etiqueta: "Togo", sispro: "768" },
  { valor: "TK", etiqueta: "Tokelau", sispro: "772" },
  { valor: "TO", etiqueta: "Tonga", sispro: "776" },
  { valor: "TT", etiqueta: "Trinidad y Tobago", sispro: "780" },
  { valor: "TN", etiqueta: "Túnez", sispro: "788" },
  { valor: "TM", etiqueta: "Turkmenistan", sispro: "795" },
  { valor: "TR", etiqueta: "Turquía", sispro: "792" },
  { valor: "TV", etiqueta: "Tuvalu", sispro: "798" },
  { valor: "UA", etiqueta: "Ucrania", sispro: "804" },
  { valor: "UG", etiqueta: "Uganda", sispro: "800" },
  { valor: "UY", etiqueta: "Uruguay", sispro: "858" },
  { valor: "UZ", etiqueta: "Uzbekistan", sispro: "860" },
  { valor: "VU", etiqueta: "Vanuatu", sispro: "548" },
  { valor: "VN", etiqueta: "Vietnam", sispro: "704" },
  { valor: "WF", etiqueta: "Wallis y Futuna", sispro: "876" },
  { valor: "YE", etiqueta: "Yemen", sispro: "887" },
  { valor: "DJ", etiqueta: "Yibuti", sispro: "262" },
  { valor: "ZM", etiqueta: "Zambia", sispro: "894" },
  { valor: "ZW", etiqueta: "Zimbabue", sispro: "716" }
];

const CAT_OCUPACION_CIUO = [
  { valor: "0110", etiqueta: "Oficiales de las Fuerzas Militares", sispro: "0110" },
  { valor: "0210", etiqueta: "Suboficiales de las Fuerzas Militares", sispro: "0210" },
  { valor: "0310", etiqueta: "Otros miembros de las Fuerzas Militares", sispro: "0310" },
  { valor: "1111", etiqueta: "Directores formuladores de políticas y normas", sispro: "1111" },
  { valor: "1112", etiqueta: "Directores del gobierno", sispro: "1112" },
  { valor: "1113", etiqueta: "Jefes de comunidades étnicas", sispro: "1113" },
  { valor: "1114", etiqueta: "Dirigentes de organizaciones con un interés específico partidos políticos, sindicatos y organizaciones sociales", sispro: "1114" },
  { valor: "1120", etiqueta: "Directores y gerentes generales", sispro: "1120" },
  { valor: "1211", etiqueta: "Directores financieros", sispro: "1211" },
  { valor: "1212", etiqueta: "Directores de recursos humanos", sispro: "1212" },
  { valor: "1213", etiqueta: "Directores de políticas y planificación", sispro: "1213" },
  { valor: "1219", etiqueta: "Directores de administración y servicios no clasificados en otros grupos primarios", sispro: "1219" },
  { valor: "1221", etiqueta: "Directores de ventas y comercialización", sispro: "1221" },
  { valor: "1222", etiqueta: "Directores de publicidad y relaciones públicas", sispro: "1222" },
  { valor: "1223", etiqueta: "Directores de investigación y desarrollo", sispro: "1223" },
  { valor: "1311", etiqueta: "Directores de producción agropecuaria y silvicultura", sispro: "1311" },
  { valor: "1312", etiqueta: "Directores de producción de piscicultura y pesca", sispro: "1312" },
  { valor: "1321", etiqueta: "Directores de industrias manufactureras", sispro: "1321" },
  { valor: "1322", etiqueta: "Directores de explotaciones de minería", sispro: "1322" },
  { valor: "1323", etiqueta: "Directores de empresas de construcción", sispro: "1323" },
  { valor: "1324", etiqueta: "Directores de empresas de abastecimiento, distribución y afines", sispro: "1324" },
  { valor: "1330", etiqueta: "Directores de servicios de tecnología de la información y las comunicaciones", sispro: "1330" },
  { valor: "1341", etiqueta: "Directores de servicios de cuidados infantiles", sispro: "1341" },
  { valor: "1342", etiqueta: "Directores de servicios de salud", sispro: "1342" },
  { valor: "1343", etiqueta: "Directores de servicios de atención a personas mayores", sispro: "1343" },
  { valor: "1344", etiqueta: "Directores de servicios de bienestar social", sispro: "1344" },
  { valor: "1345", etiqueta: "Directores de servicios de educación", sispro: "1345" },
  { valor: "1346", etiqueta: "Gerentes de sucursales de bancos, de servicios financieros y de seguros", sispro: "1346" },
  { valor: "1349", etiqueta: "Directores y gerentes de servicios profesionales no clasificados en otros grupos primarios", sispro: "1349" },
  { valor: "1411", etiqueta: "Gerentes de hoteles", sispro: "1411" },
  { valor: "1412", etiqueta: "Gerentes de restaurantes", sispro: "1412" },
  { valor: "1420", etiqueta: "Gerentes de comercios al por mayor y al por menor", sispro: "1420" },
  { valor: "1431", etiqueta: "Gerentes de centros deportivos, de esparcimiento y culturales", sispro: "1431" },
  { valor: "1439", etiqueta: "Otros gerentes de servicios no clasificados en otros grupos primarios", sispro: "1439" },
  { valor: "2111", etiqueta: "Físicos y astrónomos", sispro: "2111" },
  { valor: "2112", etiqueta: "Meteorólogos", sispro: "2112" },
  { valor: "2113", etiqueta: "Químicos", sispro: "2113" },
  { valor: "2114", etiqueta: "Geólogos y geofísicos", sispro: "2114" },
  { valor: "2120", etiqueta: "Matemáticos, actuarios y estadísticos", sispro: "2120" },
  { valor: "2131", etiqueta: "Biólogos, botánicos, zoólogos y afines", sispro: "2131" },
  { valor: "2132", etiqueta: "Agrónomos, silvicultores, zootecnistas y afines", sispro: "2132" },
  { valor: "2133", etiqueta: "Profesionales de la protección medioambiental", sispro: "2133" },
  { valor: "2141", etiqueta: "Ingenieros industriales y de producción", sispro: "2141" },
  { valor: "2142", etiqueta: "Ingenieros civiles", sispro: "2142" },
  { valor: "2143", etiqueta: "Ingenieros medioambientales", sispro: "2143" },
  { valor: "2144", etiqueta: "Ingenieros mecánicos", sispro: "2144" },
  { valor: "2145", etiqueta: "Ingenieros químicos", sispro: "2145" },
  { valor: "2146", etiqueta: "Ingenieros de minas, metalúrgicos y afines", sispro: "2146" },
  { valor: "2149", etiqueta: "Ingenieros no clasificados en otros grupos primarios", sispro: "2149" },
  { valor: "2151", etiqueta: "Ingenieros electricistas", sispro: "2151" },
  { valor: "2152", etiqueta: "Ingenieros electrónicos", sispro: "2152" },
  { valor: "2153", etiqueta: "Ingenieros de telecomunicaciones", sispro: "2153" },
  { valor: "2161", etiqueta: "Arquitectos constructores", sispro: "2161" },
  { valor: "2162", etiqueta: "Arquitectos paisajistas", sispro: "2162" },
  { valor: "2163", etiqueta: "Diseñadores de productos y de prendas", sispro: "2163" },
  { valor: "2164", etiqueta: "Planificadores urbanos, regionales y de tránsito", sispro: "2164" },
  { valor: "2165", etiqueta: "Cartógrafos y topógrafos", sispro: "2165" },
  { valor: "2166", etiqueta: "Diseñadores gráficos y multimedia", sispro: "2166" },
  { valor: "2211", etiqueta: "Médicos generales", sispro: "2211" },
  { valor: "2212", etiqueta: "Médicos especialistas", sispro: "2212" },
  { valor: "2221", etiqueta: "Profesionales de enfermería", sispro: "2221" },
  { valor: "2222", etiqueta: "Profesionales de partería", sispro: "2222" },
  { valor: "2230", etiqueta: "Profesionales de medicina tradicional y alternativa", sispro: "2230" },
  { valor: "2240", etiqueta: "Paramédicos e instrumentadores quirúrgicos", sispro: "2240" },
  { valor: "2250", etiqueta: "Veterinarios", sispro: "2250" },
  { valor: "2261", etiqueta: "Odontólogos", sispro: "2261" },
  { valor: "2262", etiqueta: "Farmacéuticos", sispro: "2262" },
  { valor: "2263", etiqueta: "Profesionales de la salud y la higiene laboral y ambiental", sispro: "2263" },
  { valor: "2264", etiqueta: "Fisioterapeutas", sispro: "2264" },
  { valor: "2265", etiqueta: "Dietistas y nutricionistas", sispro: "2265" },
  { valor: "2266", etiqueta: "Fonoaudiólogos y terapeutas del lenguaje", sispro: "2266" },
  { valor: "2267", etiqueta: "Optómetras", sispro: "2267" },
  { valor: "2269", etiqueta: "Otros profesionales de la salud no clasificados en otros grupos primarios", sispro: "2269" },
  { valor: "2310", etiqueta: "Profesores de instituciones de educación superior", sispro: "2310" },
  { valor: "2320", etiqueta: "Profesores de formación profesional", sispro: "2320" },
  { valor: "2330", etiqueta: "Profesores de educación secundaria", sispro: "2330" },
  { valor: "2341", etiqueta: "Profesores de educación primaria", sispro: "2341" },
  { valor: "2342", etiqueta: "Profesores de primera infancia", sispro: "2342" },
  { valor: "2351", etiqueta: "Especialistas en métodos pedagógicos", sispro: "2351" },
  { valor: "2352", etiqueta: "Profesores de educación especial e inclusiva", sispro: "2352" },
  { valor: "2353", etiqueta: "Otros profesores de idiomas", sispro: "2353" },
  { valor: "2354", etiqueta: "Otros profesores de música", sispro: "2354" },
  { valor: "2355", etiqueta: "Otros profesores de artes", sispro: "2355" },
  { valor: "2356", etiqueta: "Instructores de tecnología de la información", sispro: "2356" },
  { valor: "2359", etiqueta: "Otros profesionales de la educación no clasificados en otros grupos primarios", sispro: "2359" },
  { valor: "2411", etiqueta: "Contadores", sispro: "2411" },
  { valor: "2412", etiqueta: "Asesores financieros y de inversiones", sispro: "2412" },
  { valor: "2413", etiqueta: "Analistas financieros", sispro: "2413" },
  { valor: "2421", etiqueta: "Analistas de gestión y organización", sispro: "2421" },
  { valor: "2422", etiqueta: "Profesionales en políticas de administración", sispro: "2422" },
  { valor: "2423", etiqueta: "Profesionales de gestión de talento humano", sispro: "2423" },
  { valor: "2424", etiqueta: "Profesionales en formación y desarrollo de personal", sispro: "2424" },
  { valor: "2431", etiqueta: "Profesionales de la publicidad y la comercialización", sispro: "2431" },
  { valor: "2432", etiqueta: "Profesionales de relaciones públicas", sispro: "2432" },
  { valor: "2433", etiqueta: "Profesionales de ventas técnicas y médicas (excluyendo las TIC)", sispro: "2433" },
  { valor: "2434", etiqueta: "Profesionales de ventas de tecnología de la información y las comunicaciones", sispro: "2434" },
  { valor: "2511", etiqueta: "Analistas de sistemas", sispro: "2511" },
  { valor: "2512", etiqueta: "Desarrolladores de software", sispro: "2512" },
  { valor: "2513", etiqueta: "Desarrolladores web y multimedia", sispro: "2513" },
  { valor: "2514", etiqueta: "Programadores de aplicaciones", sispro: "2514" },
  { valor: "2519", etiqueta: "Desarrolladores y analistas de software y multimedia no clasificados en otros grupos primarios", sispro: "2519" },
  { valor: "2521", etiqueta: "Diseñadores y administradores de bases de datos", sispro: "2521" },
  { valor: "2522", etiqueta: "Administradores de sistemas", sispro: "2522" },
  { valor: "2523", etiqueta: "Profesionales en redes de computadores", sispro: "2523" },
  { valor: "2529", etiqueta: "Profesionales en bases de datos y en redes de computadores no clasificados en otros grupos primarios", sispro: "2529" },
  { valor: "2611", etiqueta: "Abogados", sispro: "2611" },
  { valor: "2612", etiqueta: "Jueces", sispro: "2612" },
  { valor: "2619", etiqueta: "Profesionales en derecho no clasificados en otros grupos primarios", sispro: "2619" },
  { valor: "2621", etiqueta: "Archivistas y curadores de arte", sispro: "2621" },
  { valor: "2622", etiqueta: "Bibliotecarios, documentalistas y afines", sispro: "2622" },
  { valor: "2631", etiqueta: "Economistas", sispro: "2631" },
  { valor: "2632", etiqueta: "Sociólogos, antropólogos y afines", sispro: "2632" },
  { valor: "2633", etiqueta: "Filósofos, historiadores y especialistas en ciencias políticas", sispro: "2633" },
  { valor: "2634", etiqueta: "Psicólogos", sispro: "2634" },
  { valor: "2635", etiqueta: "Profesionales del trabajo social y consejeros", sispro: "2635" },
  { valor: "2636", etiqueta: "Profesionales religiosos", sispro: "2636" },
  { valor: "2641", etiqueta: "Autores y otros escritores", sispro: "2641" },
  { valor: "2642", etiqueta: "Periodistas", sispro: "2642" },
  { valor: "2643", etiqueta: "Traductores, intérpretes y otros lingüistas", sispro: "2643" },
  { valor: "2651", etiqueta: "Escultores, pintores artísticos y afines", sispro: "2651" },
  { valor: "2652", etiqueta: "Compositores, músicos y cantantes", sispro: "2652" },
  { valor: "2653", etiqueta: "Coreógrafos y bailarines", sispro: "2653" },
  { valor: "2654", etiqueta: "Directores y productores de cine, de teatro y afines", sispro: "2654" },
  { valor: "2655", etiqueta: "Actores", sispro: "2655" },
  { valor: "2656", etiqueta: "Locutores de radio, televisión y otros medios de comunicación", sispro: "2656" },
  { valor: "2659", etiqueta: "Artistas creativos e interpretativos no clasificados en otros grupos primarios", sispro: "2659" },
  { valor: "3111", etiqueta: "Técnicos en ciencias físicas y químicas", sispro: "3111" },
  { valor: "3112", etiqueta: "Técnicos en ingeniería civil", sispro: "3112" },
  { valor: "3113", etiqueta: "Electrotécnicos", sispro: "3113" },
  { valor: "3114", etiqueta: "Técnicos en electrónica", sispro: "3114" },
  { valor: "3115", etiqueta: "Técnicos en ingeniería mecánica", sispro: "3115" },
  { valor: "3116", etiqueta: "Técnicos en química industrial", sispro: "3116" },
  { valor: "3117", etiqueta: "Técnicos de minas y metalurgia", sispro: "3117" },
  { valor: "3118", etiqueta: "Delineantes y dibujantes técnicos", sispro: "3118" },
  { valor: "3119", etiqueta: "Técnicos en ciencias físicas y en ingeniería no clasificados en otros grupos primarios", sispro: "3119" },
  { valor: "3121", etiqueta: "Supervisores de minas", sispro: "3121" },
  { valor: "3122", etiqueta: "Supervisores de industrias manufactureras", sispro: "3122" },
  { valor: "3123", etiqueta: "Supervisores de la construcción", sispro: "3123" },
  { valor: "3131", etiqueta: "Operadores de plantas de producción de energía", sispro: "3131" },
  { valor: "3132", etiqueta: "Operadores de incineradores, instalaciones de tratamiento de agua y afines", sispro: "3132" },
  { valor: "3133", etiqueta: "Controladores de instalaciones de procesamiento de productos químicos", sispro: "3133" },
  { valor: "3134", etiqueta: "Operadores de instalaciones de refinación de petróleo y gas natural", sispro: "3134" },
  { valor: "3135", etiqueta: "Operadores de procesos de producción de metales", sispro: "3135" },
  { valor: "3139", etiqueta: "Técnicos en control de procesos no clasificados en otros grupos primarios", sispro: "3139" },
  { valor: "3141", etiqueta: "Técnicos en ciencias biológicas (excluyendo la medicina)", sispro: "3141" },
  { valor: "3142", etiqueta: "Técnicos agropecuarios", sispro: "3142" },
  { valor: "3143", etiqueta: "Técnicos forestales", sispro: "3143" },
  { valor: "3151", etiqueta: "Oficiales maquinistas en navegación", sispro: "3151" },
  { valor: "3152", etiqueta: "Capitanes, oficiales de cubierta y prácticos", sispro: "3152" },
  { valor: "3153", etiqueta: "Pilotos de aviación y afines", sispro: "3153" },
  { valor: "3154", etiqueta: "Controladores de tráfico aéreo y marítimo", sispro: "3154" },
  { valor: "3155", etiqueta: "Técnicos en seguridad aeronáutica", sispro: "3155" },
  { valor: "3211", etiqueta: "Técnicos en aparatos de diagnóstico y tratamiento médico", sispro: "3211" },
  { valor: "3212", etiqueta: "Técnicos de laboratorios médicos", sispro: "3212" },
  { valor: "3213", etiqueta: "Técnicos y asistentes farmacéuticos", sispro: "3213" },
  { valor: "3214", etiqueta: "Técnicos de prótesis médicas y dentales", sispro: "3214" },
  { valor: "3221", etiqueta: "Técnicos y profesionales del nivel medio en enfermería", sispro: "3221" },
  { valor: "3222", etiqueta: "Técnicos y profesionales del nivel medio en partería", sispro: "3222" },
  { valor: "3230", etiqueta: "Técnicos y profesionales del nivel medio en medicina tradicional y alternativa", sispro: "3230" },
  { valor: "3240", etiqueta: "Técnicos y asistentes veterinarios", sispro: "3240" },
  { valor: "3251", etiqueta: "Higienistas y asistentes odontológicos", sispro: "3251" },
  { valor: "3252", etiqueta: "Técnicos en documentación sanitaria", sispro: "3252" },
  { valor: "3253", etiqueta: "Trabajadores comunitarios de la salud", sispro: "3253" },
  { valor: "3254", etiqueta: "Técnicos en optometría y ópticas", sispro: "3254" },
  { valor: "3255", etiqueta: "Técnicos y asistentes terapeutas", sispro: "3255" },
  { valor: "3256", etiqueta: "Asistentes médicos", sispro: "3256" },
  { valor: "3257", etiqueta: "Inspectores de seguridad, salud ocupacional, medioambiental y afines", sispro: "3257" },
  { valor: "3258", etiqueta: "Técnicos en atención prehospitalaria", sispro: "3258" },
  { valor: "3259", etiqueta: "Otros técnicos y profesionales del nivel medio de la salud, no clasificados en otros grupos primarios", sispro: "3259" },
  { valor: "3311", etiqueta: "Agentes de bolsa, cambio y otros servicios financieros", sispro: "3311" },
  { valor: "3312", etiqueta: "Analistas de préstamos y créditos", sispro: "3312" },
  { valor: "3313", etiqueta: "Técnicos de contabilidad y afines", sispro: "3313" },
  { valor: "3314", etiqueta: "Técnicos y profesionales del nivel medio de servicios estadísticos, matemáticos y afines", sispro: "3314" },
  { valor: "3315", etiqueta: "Tasadores y evaluadores", sispro: "3315" },
  { valor: "3321", etiqueta: "Agentes de seguros", sispro: "3321" },
  { valor: "3322", etiqueta: "Representantes comerciales", sispro: "3322" },
  { valor: "3323", etiqueta: "Agentes de compras", sispro: "3323" },
  { valor: "3324", etiqueta: "Agentes de operaciones comerciales y consignatarios", sispro: "3324" },
  { valor: "3331", etiqueta: "Declarantes o gestores de aduana", sispro: "3331" },
  { valor: "3332", etiqueta: "Organizadores de conferencias y eventos", sispro: "3332" },
  { valor: "3333", etiqueta: "Agentes de empleo y contratistas de mano de obra", sispro: "3333" },
  { valor: "3334", etiqueta: "Agentes inmobiliarios", sispro: "3334" },
  { valor: "3339", etiqueta: "Agentes de servicios comerciales no clasificados en otros grupos primarios", sispro: "3339" },
  { valor: "3341", etiqueta: "Supervisores de oficina", sispro: "3341" },
  { valor: "3342", etiqueta: "Secretarios jurídicos", sispro: "3342" },
  { valor: "3343", etiqueta: "Secretarios administrativos y ejecutivos", sispro: "3343" },
  { valor: "3344", etiqueta: "Secretarios médicos", sispro: "3344" },
  { valor: "3351", etiqueta: "Agentes de aduana e inspectores de frontera", sispro: "3351" },
  { valor: "3352", etiqueta: "Agentes de administración tributaria", sispro: "3352" },
  { valor: "3353", etiqueta: "Agentes de servicios de seguridad social", sispro: "3353" },
  { valor: "3354", etiqueta: "Agentes gubernamentales de expedición de licencias", sispro: "3354" },
  { valor: "3355", etiqueta: "Inspectores de policía y detectives", sispro: "3355" },
  { valor: "3359", etiqueta: "Agentes de gobierno y profesionales del nivel medio para la aplicación de regulaciones no clasificados en otros grupos primarios", sispro: "3359" },
  { valor: "3411", etiqueta: "Técnicos y profesionales del nivel medio del derecho de servicios legales y afines", sispro: "3411" },
  { valor: "3412", etiqueta: "Trabajadores y asistentes sociales", sispro: "3412" },
  { valor: "3413", etiqueta: "Auxiliares laicos de las religiones", sispro: "3413" },
  { valor: "3421", etiqueta: "Atletas y deportistas", sispro: "3421" },
  { valor: "3422", etiqueta: "Entrenadores, instructores y árbitros de actividades deportivas", sispro: "3422" },
  { valor: "3423", etiqueta: "Instructores de educación física y actividades recreativas", sispro: "3423" },
  { valor: "3431", etiqueta: "Fotógrafos", sispro: "3431" },
  { valor: "3432", etiqueta: "Diseñadores y decoradores de interiores", sispro: "3432" },
  { valor: "3433", etiqueta: "Técnicos en galerías de arte, museos y bibliotecas", sispro: "3433" },
  { valor: "3434", etiqueta: "Chefs", sispro: "3434" },
  { valor: "3435", etiqueta: "Otros técnicos y profesionales del nivel medio en actividades culturales y artísticas", sispro: "3435" },
  { valor: "3511", etiqueta: "Técnicos en operaciones de tecnología de la información y las comunicaciones", sispro: "3511" },
  { valor: "3512", etiqueta: "Técnicos en asistencia y soporte al usuario de tecnología de la información y las comunicaciones", sispro: "3512" },
  { valor: "3513", etiqueta: "Técnicos en redes y sistemas de computación", sispro: "3513" },
  { valor: "3514", etiqueta: "Técnicos de la Web", sispro: "3514" },
  { valor: "3521", etiqueta: "Técnicos de radiodifusión y grabación audio visual", sispro: "3521" },
  { valor: "3522", etiqueta: "Técnicos de ingeniería de las telecomunicaciones", sispro: "3522" },
  { valor: "4110", etiqueta: "Oficinistas generales", sispro: "4110" },
  { valor: "4120", etiqueta: "Secretarios generales", sispro: "4120" },
  { valor: "4131", etiqueta: "Operadores de máquinas de procesamiento de texto y mecanógrafos", sispro: "4131" },
  { valor: "4132", etiqueta: "Grabadores de datos", sispro: "4132" },
  { valor: "4211", etiqueta: "Cajeros de bancos y afines", sispro: "4211" },
  { valor: "4212", etiqueta: "Receptores de apuestas y afines", sispro: "4212" },
  { valor: "4213", etiqueta: "Prestamistas", sispro: "4213" },
  { valor: "4214", etiqueta: "Cobradores y afines", sispro: "4214" },
  { valor: "4221", etiqueta: "Empleados y consultores de viajes", sispro: "4221" },
  { valor: "4222", etiqueta: "Empleados de centros de llamadas", sispro: "4222" },
  { valor: "4223", etiqueta: "Telefonistas", sispro: "4223" },
  { valor: "4224", etiqueta: "Recepcionistas de hoteles", sispro: "4224" },
  { valor: "4225", etiqueta: "Empleados de ventanillas de informaciones", sispro: "4225" },
  { valor: "4226", etiqueta: "Recepcionistas generales", sispro: "4226" },
  { valor: "4227", etiqueta: "Entrevistadores de encuestas y de investigaciones de mercados", sispro: "4227" },
  { valor: "4229", etiqueta: "Otros empleados de servicios de información al cliente no clasificados en otros grupos primarios", sispro: "4229" },
  { valor: "4311", etiqueta: "Auxiliares de contabilidad y cálculo de costos", sispro: "4311" },
  { valor: "4312", etiqueta: "Auxiliares de servicios estadísticos, financieros y de seguros", sispro: "4312" },
  { valor: "4313", etiqueta: "Auxiliares encargados de las nóminas", sispro: "4313" },
  { valor: "4321", etiqueta: "Empleados de control de abastecimientos e inventario", sispro: "4321" },
  { valor: "4322", etiqueta: "Empleados de servicios de apoyo a la producción", sispro: "4322" },
  { valor: "4323", etiqueta: "Empleados de servicios de transporte", sispro: "4323" },
  { valor: "4411", etiqueta: "Empleados de bibliotecas", sispro: "4411" },
  { valor: "4412", etiqueta: "Empleados de servicios de correos", sispro: "4412" },
  { valor: "4413", etiqueta: "Codificadores de datos, correctores de pruebas de imprenta y afines", sispro: "4413" },
  { valor: "4414", etiqueta: "Escribientes públicos y afines", sispro: "4414" },
  { valor: "4415", etiqueta: "Empleados de archivos", sispro: "4415" },
  { valor: "4416", etiqueta: "Empleados del servicio de personal", sispro: "4416" },
  { valor: "4419", etiqueta: "Otro personal de apoyo administrativo no clasificados en otros grupos primarios", sispro: "4419" },
  { valor: "5111", etiqueta: "Personal de servicio a pasajeros", sispro: "5111" },
  { valor: "5112", etiqueta: "Revisores y cobradores de los transportes públicos", sispro: "5112" },
  { valor: "5113", etiqueta: "Guías", sispro: "5113" },
  { valor: "5120", etiqueta: "Cocineros", sispro: "5120" },
  { valor: "5131", etiqueta: "Meseros", sispro: "5131" },
  { valor: "5132", etiqueta: "Bármanes", sispro: "5132" },
  { valor: "5141", etiqueta: "Peluqueros", sispro: "5141" },
  { valor: "5142", etiqueta: "Especialistas en tratamientos de belleza y afines", sispro: "5142" },
  { valor: "5151", etiqueta: "Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos", sispro: "5151" },
  { valor: "5152", etiqueta: "Mayordomos domésticos", sispro: "5152" },
  { valor: "5153", etiqueta: "Conserjes y afines", sispro: "5153" },
  { valor: "5161", etiqueta: "Astrólogos, adivinos y trabajadores afines", sispro: "5161" },
  { valor: "5162", etiqueta: "Acompañantes", sispro: "5162" },
  { valor: "5163", etiqueta: "Personal de servicios funerarios y embalsamadores", sispro: "5163" },
  { valor: "5164", etiqueta: "Cuidadores de animales", sispro: "5164" },
  { valor: "5165", etiqueta: "Instructores de conducción", sispro: "5165" },
  { valor: "5169", etiqueta: "Otros trabajadores de servicios personales no clasificados en otros grupos primarios", sispro: "5169" },
  { valor: "5211", etiqueta: "Vendedores de quioscos y de puestos de mercado", sispro: "5211" },
  { valor: "5212", etiqueta: "Vendedores ambulantes de alimentos preparados para consumo inmediato", sispro: "5212" },
  { valor: "5221", etiqueta: "Comerciantes de tiendas", sispro: "5221" },
  { valor: "5222", etiqueta: "Supervisores de tiendas y almacenes", sispro: "5222" },
  { valor: "5223", etiqueta: "Vendedores y auxiliares de venta en tiendas, almacenes y afines", sispro: "5223" },
  { valor: "5230", etiqueta: "Cajeros de comercio, taquilleros y expendedores de boletas", sispro: "5230" },
  { valor: "5241", etiqueta: "Modelos de moda, arte y publicidad", sispro: "5241" },
  { valor: "5242", etiqueta: "Demostradores de tiendas, almacenes y afines", sispro: "5242" },
  { valor: "5243", etiqueta: "Vendedores puerta a puerta", sispro: "5243" },
  { valor: "5244", etiqueta: "Vendedores a través de medios tecnológicos", sispro: "5244" },
  { valor: "5245", etiqueta: "Expendedores de combustibles para vehículos", sispro: "5245" },
  { valor: "5246", etiqueta: "Vendedores de comidas al mostrador", sispro: "5246" },
  { valor: "5249", etiqueta: "Otros vendedores no clasificados en otros grupos primarios", sispro: "5249" },
  { valor: "5311", etiqueta: "Cuidadores de niños", sispro: "5311" },
  { valor: "5312", etiqueta: "Auxiliares de maestros", sispro: "5312" },
  { valor: "5321", etiqueta: "Trabajadores de los cuidados personales en instituciones", sispro: "5321" },
  { valor: "5322", etiqueta: "Trabajadores de los cuidados personales a domicilio", sispro: "5322" },
  { valor: "5329", etiqueta: "Trabajadores de los cuidados personales en servicios de salud no clasificados en otros grupos primarios", sispro: "5329" },
  { valor: "5411", etiqueta: "Bomberos y rescatistas", sispro: "5411" },
  { valor: "5412", etiqueta: "Policías", sispro: "5412" },
  { valor: "5413", etiqueta: "Guardianes de prisión", sispro: "5413" },
  { valor: "5414", etiqueta: "Guardias de seguridad", sispro: "5414" },
  { valor: "5419", etiqueta: "Personal de los servicios de protección no clasificadosen otros grupos primarios", sispro: "5419" },
  { valor: "6111", etiqueta: "Agricultores y trabajadores calificados de cultivos extensivos", sispro: "6111" },
  { valor: "6112", etiqueta: "Agricultores y trabajadores calificados de plantaciones de árboles y arbustos", sispro: "6112" },
  { valor: "6113", etiqueta: "Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines", sispro: "6113" },
  { valor: "6114", etiqueta: "Agricultores y trabajadores calificados de cultivos mixtos", sispro: "6114" },
  { valor: "6121", etiqueta: "Criadores de ganado y trabajadores de la cría de animales domésticos (excepto aves de corral)", sispro: "6121" },
  { valor: "6122", etiqueta: "Avicultores y trabajadores calificados de la avicultura", sispro: "6122" },
  { valor: "6123", etiqueta: "Criadores y trabajadores calificados de la apicultura y la sericicultura", sispro: "6123" },
  { valor: "6129", etiqueta: "Criadores y trabajadores pecuarios calificados, avicultores y criadores de insectos no clasificados en otros grupos primarios", sispro: "6129" },
  { valor: "6130", etiqueta: "Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado", sispro: "6130" },
  { valor: "6210", etiqueta: "Trabajadores forestales calificados y afines", sispro: "6210" },
  { valor: "6221", etiqueta: "Trabajadores de explotaciones de acuicultura", sispro: "6221" },
  { valor: "6222", etiqueta: "Pescadores de agua dulce y en aguas costeras", sispro: "6222" },
  { valor: "6223", etiqueta: "Pescadores de alta mar", sispro: "6223" },
  { valor: "6224", etiqueta: "Cazadores y tramperos", sispro: "6224" },
  { valor: "6310", etiqueta: "Trabajadores agrícolas de subsistencia", sispro: "6310" },
  { valor: "6320", etiqueta: "Trabajadores pecuarios de subsistencia", sispro: "6320" },
  { valor: "6330", etiqueta: "Trabajadores agropecuarios de subsistencia", sispro: "6330" },
  { valor: "6340", etiqueta: "Pescadores, cazadores, tramperos y recolectores de subsistencia", sispro: "6340" },
  { valor: "7111", etiqueta: "Constructores de casas", sispro: "7111" },
  { valor: "7112", etiqueta: "Albañiles", sispro: "7112" },
  { valor: "7113", etiqueta: "Labrantes, tronzadores y grabadores de piedra", sispro: "7113" },
  { valor: "7114", etiqueta: "Operarios en cemento armado, enfoscadores y afines", sispro: "7114" },
  { valor: "7115", etiqueta: "Carpinteros de armar y de obra blanca", sispro: "7115" },
  { valor: "7119", etiqueta: "Oficiales y operarios de la construcción de obra gruesa y afines no clasificados en otros grupos primarios", sispro: "7119" },
  { valor: "7121", etiqueta: "Techadores", sispro: "7121" },
  { valor: "7122", etiqueta: "Enchapadores, parqueteros y colocadores de suelos", sispro: "7122" },
  { valor: "7123", etiqueta: "Revocadores", sispro: "7123" },
  { valor: "7124", etiqueta: "Instaladores de material aislante y de insonorización", sispro: "7124" },
  { valor: "7125", etiqueta: "Cristaleros", sispro: "7125" },
  { valor: "7126", etiqueta: "Fontaneros e instaladores de tuberías", sispro: "7126" },
  { valor: "7127", etiqueta: "Mecánicos montadores de aire acondicionado y refrigeración", sispro: "7127" },
  { valor: "7131", etiqueta: "Pintores y empapeladores", sispro: "7131" },
  { valor: "7132", etiqueta: "Barnizadores y afines", sispro: "7132" },
  { valor: "7133", etiqueta: "Limpiadores de fachadas y deshollinadores", sispro: "7133" },
  { valor: "7211", etiqueta: "Moldeadores y macheros", sispro: "7211" },
  { valor: "7212", etiqueta: "Soldadores y oxicortadores", sispro: "7212" },
  { valor: "7213", etiqueta: "Chapistas y caldereros", sispro: "7213" },
  { valor: "7214", etiqueta: "Montadores de estructuras metálicas", sispro: "7214" },
  { valor: "7215", etiqueta: "Aparejadores y empalmadores de cables", sispro: "7215" },
  { valor: "7221", etiqueta: "Herreros y forjadores", sispro: "7221" },
  { valor: "7222", etiqueta: "Herramentistas y afines", sispro: "7222" },
  { valor: "7223", etiqueta: "Ajustadores y operadores de máquinas herramientas", sispro: "7223" },
  { valor: "7224", etiqueta: "Pulidores de metales y afiladores de herramientas", sispro: "7224" },
  { valor: "7231", etiqueta: "Mecánicos y reparadores de vehículos de motor", sispro: "7231" },
  { valor: "7232", etiqueta: "Mecánicos y reparadores de sistemas y motores de aeronaves", sispro: "7232" },
  { valor: "7233", etiqueta: "Mecánicos y reparadores de máquinas agrícolas e industriales", sispro: "7233" },
  { valor: "7234", etiqueta: "Reparadores de bicicletas y afines", sispro: "7234" },
  { valor: "7311", etiqueta: "Mecánicos y reparadores de instrumentos de precisión", sispro: "7311" },
  { valor: "7312", etiqueta: "Fabricantes y afinadores de instrumentos musicales", sispro: "7312" },
  { valor: "7314", etiqueta: "Alfareros y ceramistas (barro y arcilla)", sispro: "7314" },
  { valor: "7315", etiqueta: "Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio", sispro: "7315" },
  { valor: "7316", etiqueta: "Rotulistas, pintores decorativos y grabadores", sispro: "7316" },
  { valor: "7321", etiqueta: "Preimpresores y afines", sispro: "7321" },
  { valor: "7322", etiqueta: "Impresores", sispro: "7322" },
  { valor: "7323", etiqueta: "Encuadernadores y afines", sispro: "7323" },
  { valor: "7331", etiqueta: "Tejedores con telares", sispro: "7331" },
  { valor: "7332", etiqueta: "Tejedores con agujas", sispro: "7332" },
  { valor: "7333", etiqueta: "Otros tejedores", sispro: "7333" },
  { valor: "7341", etiqueta: "Cesteros y mimbreros", sispro: "7341" },
  { valor: "7342", etiqueta: "Sombrereros artesanales", sispro: "7342" },
  { valor: "7351", etiqueta: "Talladores piezas artesanales de madera", sispro: "7351" },
  { valor: "7352", etiqueta: "Decoradores de piezas artesanales en madera", sispro: "7352" },
  { valor: "7361", etiqueta: "Joyeros", sispro: "7361" },
  { valor: "7362", etiqueta: "Orfebres y plateros", sispro: "7362" },
  { valor: "7363", etiqueta: "Bisuteros", sispro: "7363" },
  { valor: "7370", etiqueta: "Artesanos del cuero", sispro: "7370" },
  { valor: "7391", etiqueta: "Artesanos de papel", sispro: "7391" },
  { valor: "7392", etiqueta: "Artesanos del hierro y otros metales", sispro: "7392" },
  { valor: "7393", etiqueta: "Artesanos de las semillas y cortezas vegetales", sispro: "7393" },
  { valor: "7399", etiqueta: "Artesanos de otros materiales no clasificados en otros grupos primarios", sispro: "7399" },
  { valor: "7411", etiqueta: "Electricistas de obras y afines", sispro: "7411" },
  { valor: "7412", etiqueta: "Mecánicos y ajustadores electricistas", sispro: "7412" },
  { valor: "7413", etiqueta: "Instaladores y reparadores de líneas eléctricas", sispro: "7413" },
  { valor: "7421", etiqueta: "Mecánicos y reparadores en electrónica", sispro: "7421" },
  { valor: "7422", etiqueta: "Instaladores y reparadores en tecnología de la información y las comunicaciones", sispro: "7422" },
  { valor: "7511", etiqueta: "Carniceros, pescaderos y afines", sispro: "7511" },
  { valor: "7512", etiqueta: "Panaderos, pasteleros y confiteros", sispro: "7512" },
  { valor: "7513", etiqueta: "Operarios de la elaboración de productos lácteos", sispro: "7513" },
  { valor: "7514", etiqueta: "Operarios de la conservación de frutas, legumbres, verduras y afines", sispro: "7514" },
  { valor: "7515", etiqueta: "Catadores y clasificadores de alimentos y bebidas", sispro: "7515" },
  { valor: "7516", etiqueta: "Preparadores y elaboradores de tabaco y sus productos", sispro: "7516" },
  { valor: "7521", etiqueta: "Operarios del tratamiento de la madera", sispro: "7521" },
  { valor: "7522", etiqueta: "Ebanistas y carpinteros (excluye carpinteros de armar y de obra blanca)", sispro: "7522" },
  { valor: "7523", etiqueta: "Ajustadores y operadores de máquinas para trabajar madera", sispro: "7523" },
  { valor: "7531", etiqueta: "Sastres, modistos, peleteros y sombrereros", sispro: "7531" },
  { valor: "7532", etiqueta: "Patronistas y cortadores de tela, cuero y afines", sispro: "7532" },
  { valor: "7533", etiqueta: "Costureros, bordadores y afines", sispro: "7533" },
  { valor: "7534", etiqueta: "Tapiceros, colchoneros y afines", sispro: "7534" },
  { valor: "7535", etiqueta: "Apelambradores, pellejeros y curtidores", sispro: "7535" },
  { valor: "7536", etiqueta: "Zapateros y afines", sispro: "7536" },
  { valor: "7541", etiqueta: "Buzos", sispro: "7541" },
  { valor: "7542", etiqueta: "Dinamiteros y pegadores", sispro: "7542" },
  { valor: "7543", etiqueta: "Clasificadores y probadores de productos (excluyendo alimentos y bebidas)", sispro: "7543" },
  { valor: "7544", etiqueta: "Fumigadores y otros controladores de plagas y malas hierbas", sispro: "7544" },
  { valor: "7549", etiqueta: "Otros oficiales, operarios y oficios relacionados no clasificados en otros grupos primarios", sispro: "7549" },
  { valor: "8111", etiqueta: "Mineros y operadores de instalaciones mineras", sispro: "8111" },
  { valor: "8112", etiqueta: "Operadores de instalaciones de procesamiento de minerales y rocas", sispro: "8112" },
  { valor: "8113", etiqueta: "Perforadores y sondistas de pozos y afines", sispro: "8113" },
  { valor: "8114", etiqueta: "Operadores de máquinas para fabricar cemento y otros productos minerales", sispro: "8114" },
  { valor: "8121", etiqueta: "Operadores de instalaciones de procesamiento de metales", sispro: "8121" },
  { valor: "8122", etiqueta: "Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales", sispro: "8122" },
  { valor: "8131", etiqueta: "Operadores de plantas y máquinas de productos químicos", sispro: "8131" },
  { valor: "8132", etiqueta: "Operadores de máquinas para fabricar productos fotográficos", sispro: "8132" },
  { valor: "8141", etiqueta: "Operadores de máquinas para fabricar productos de caucho", sispro: "8141" },
  { valor: "8142", etiqueta: "Operadores de máquinas para fabricar productos de material plástico", sispro: "8142" },
  { valor: "8143", etiqueta: "Operadores de máquinas para fabricar productos de papel", sispro: "8143" },
  { valor: "8151", etiqueta: "Operadores de máquinas de preparación de fibras, hilado y devanado", sispro: "8151" },
  { valor: "8152", etiqueta: "Operadores de telares y otras máquinas tejedoras", sispro: "8152" },
  { valor: "8153", etiqueta: "Operadores de máquinas de coser", sispro: "8153" },
  { valor: "8154", etiqueta: "Operadores de máquinas de blanqueamiento, teñido y limpieza de tejidos", sispro: "8154" },
  { valor: "8155", etiqueta: "Operadores de máquinas de tratamiento de pieles y cueros", sispro: "8155" },
  { valor: "8156", etiqueta: "Operadores de máquinas para la fabricación de calzado y afines", sispro: "8156" },
  { valor: "8157", etiqueta: "Operadores de máquinas de lavandería", sispro: "8157" },
  { valor: "8159", etiqueta: "Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero no clasificados en otros grupos primarios", sispro: "8159" },
  { valor: "8160", etiqueta: "Operadores de máquinas para elaborar alimentos y productos afines", sispro: "8160" },
  { valor: "8171", etiqueta: "Operadores de instalaciones para la preparación de pasta para papel y papel", sispro: "8171" },
  { valor: "8172", etiqueta: "Operadores de instalaciones de procesamiento de la madera", sispro: "8172" },
  { valor: "8181", etiqueta: "Operadores de máquinas y de instalaciones para elaborar productos de vidrio y cerámica", sispro: "8181" },
  { valor: "8182", etiqueta: "Operadores de máquinas de vapor y calderas", sispro: "8182" },
  { valor: "8183", etiqueta: "Operadores de máquinas de embalaje, embotellamiento y etiquetado", sispro: "8183" },
  { valor: "8189", etiqueta: "Otros operadores de máquinas y de instalaciones fijas no clasificados en otros grupos primarios", sispro: "8189" },
  { valor: "8211", etiqueta: "Ensambladores de maquinaria mecánica", sispro: "8211" },
  { valor: "8212", etiqueta: "Ensambladores de equipos eléctricos y electrónicos", sispro: "8212" },
  { valor: "8219", etiqueta: "Ensambladores no clasificados bajo otros grupos primarios", sispro: "8219" },
  { valor: "8311", etiqueta: "Maquinistas de locomotoras", sispro: "8311" },
  { valor: "8312", etiqueta: "Guardafrenos, guardagujas y agentes de maniobras", sispro: "8312" },
  { valor: "8321", etiqueta: "Conductores de motocicletas", sispro: "8321" },
  { valor: "8323", etiqueta: "Conductores de camionetas y vehículos livianos", sispro: "8323" },
  { valor: "8324", etiqueta: "Conductores de taxis", sispro: "8324" },
  { valor: "8331", etiqueta: "Conductores de buses, microbuses y tranvías", sispro: "8331" },
  { valor: "8332", etiqueta: "Conductores de camiones y vehículos pesados", sispro: "8332" },
  { valor: "8341", etiqueta: "Operadores de maquinaria agrícola y forestal móvil", sispro: "8341" },
  { valor: "8342", etiqueta: "Operadores de máquinas de movimiento de tierras, construcción de vías y afines", sispro: "8342" },
  { valor: "8343", etiqueta: "Operadores de grúas, aparatos elevadores y afines", sispro: "8343" },
  { valor: "8344", etiqueta: "Operadores de montacargas", sispro: "8344" },
  { valor: "8350", etiqueta: "Marineros de cubierta y afines", sispro: "8350" },
  { valor: "9111", etiqueta: "Personal doméstico", sispro: "9111" },
  { valor: "9112", etiqueta: "Aseadores de oficinas, hoteles y otros establecimientos", sispro: "9112" },
  { valor: "9121", etiqueta: "Lavanderos y planchadores manuales", sispro: "9121" },
  { valor: "9122", etiqueta: "Lavadores de vehículos", sispro: "9122" },
  { valor: "9123", etiqueta: "Lavadores de ventanas", sispro: "9123" },
  { valor: "9129", etiqueta: "Otro personal de limpieza no clasificados bajo otros grupos primarios", sispro: "9129" },
  { valor: "9211", etiqueta: "Obreros y peones de explotaciones agrícolas", sispro: "9211" },
  { valor: "9212", etiqueta: "Obreros y peones de explotaciones ganaderas", sispro: "9212" },
  { valor: "9213", etiqueta: "Obreros y peones de explotaciones agropecuarias", sispro: "9213" },
  { valor: "9214", etiqueta: "Obreros y peones de jardinería y horticultura", sispro: "9214" },
  { valor: "9215", etiqueta: "Obreros y peones forestales", sispro: "9215" },
  { valor: "9216", etiqueta: "Obreros y peones de pesca y acuicultura", sispro: "9216" },
  { valor: "9311", etiqueta: "Obreros y peones de minas y canteras", sispro: "9311" },
  { valor: "9312", etiqueta: "Obreros y peones de obras públicas y mantenimiento", sispro: "9312" },
  { valor: "9313", etiqueta: "Obreros y peones de la construcción de edificios", sispro: "9313" },
  { valor: "9321", etiqueta: "Empacadores manuales", sispro: "9321" },
  { valor: "9329", etiqueta: "Obreros y peones de la industria manufacturera no clasificados en otros grupos primarios", sispro: "9329" },
  { valor: "9331", etiqueta: "Conductores de vehículos accionados a pedal o a brazo", sispro: "9331" },
  { valor: "9332", etiqueta: "Conductores de vehículos y máquinas de tracción animal", sispro: "9332" },
  { valor: "9333", etiqueta: "Obreros y peones de carga", sispro: "9333" },
  { valor: "9334", etiqueta: "Surtidores de estanterías", sispro: "9334" },
  { valor: "9411", etiqueta: "Cocineros de comidas rápidas", sispro: "9411" },
  { valor: "9412", etiqueta: "Ayudantes de cocina", sispro: "9412" },
  { valor: "9510", etiqueta: "Trabajadores ambulantes de servicios y afines", sispro: "9510" },
  { valor: "9520", etiqueta: "Vendedores ambulantes (excluyendo comidas de preparación inmediata)", sispro: "9520" },
  { valor: "9611", etiqueta: "Recolectores de basura y material reciclable", sispro: "9611" },
  { valor: "9612", etiqueta: "Clasificadores de desechos", sispro: "9612" },
  { valor: "9613", etiqueta: "Barrenderos y afines", sispro: "9613" },
  { valor: "9621", etiqueta: "Mensajeros, mandaderos, maleteros y repartidores", sispro: "9621" },
  { valor: "9622", etiqueta: "Personas que realizan trabajos varios", sispro: "9622" },
  { valor: "9624", etiqueta: "Acarreadores de agua y recolectores de leña", sispro: "9624" },
  { valor: "9625", etiqueta: "Recolectores de dinero y surtidores de máquinas de venta automática", sispro: "9625" },
  { valor: "9626", etiqueta: "Lectores de medidores", sispro: "9626" },
  { valor: "9629", etiqueta: "Otras ocupaciones elementales no clasificadas en otros grupos primarios", sispro: "9629" },
  { valor: "9998", etiqueta: "Jubilado, desempleado, ama de casa, estudiante, dedicación al hogar, menor de edad", sispro: "9998" },
  { valor: "9999", etiqueta: "En los casos en que no se tiene esta información registrar", sispro: "9999" }
];

/* `regimen` según SISPRO: S subsidiado, C contributivo, P excepción, E especial. */
const CAT_EAPB = [
  { valor: "EPSI03", etiqueta: "AIC EPSI -ASOCIACION INDIGENA DEL CAUCA", regimen: "subsidiado", nit: "817001773", sispro: "EPSI03" },
  { valor: "EPS001", etiqueta: "ALIANSALUD EPS", regimen: "contributivo", nit: "830113831", sispro: "EPS001" },
  { valor: "EPS040", etiqueta: "ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. \"SAVIA SALUD EPS\"", regimen: "contributivo", nit: "900604350", sispro: "EPS040" },
  { valor: "EPSS40", etiqueta: "ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. \"SAVIA SALUD EPS\"", regimen: "subsidiado", nit: "900604350", sispro: "EPSS40" },
  { valor: "EPSI04", etiqueta: "ANAS WAYUU EPSI", regimen: "subsidiado", nit: "839000495", sispro: "EPSI04" },
  { valor: "ESS062", etiqueta: "ASMET - ASOCIACIÓN MUTUAL LA ESPERANZA DE EL TAMBO ASMET ESS", regimen: "subsidiado", nit: "817000248", sispro: "ESS062" },
  { valor: "ESS076", etiqueta: "ASOCIACION MUTUAL BARRIOS UNIDOS DE QUIBDO", regimen: "subsidiado", nit: "818000140", sispro: "ESS076" },
  { valor: "ESC207", etiqueta: "ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS", regimen: "contributivo", nit: "806008394", sispro: "ESC207" },
  { valor: "ESS207", etiqueta: "ASOCIACION MUTUAL SER EPS-S", regimen: "subsidiado", nit: "806008394", sispro: "ESS207" },
  { valor: "CCF018", etiqueta: "CAFAM", regimen: "subsidiado", nit: "860013570", sispro: "CCF018" },
  { valor: "EPS003", etiqueta: "CAFESALUD EPS", regimen: "contributivo", nit: "800140949", sispro: "EPS003" },
  { valor: "EPSS03", etiqueta: "CAFESALUD EPS", regimen: "subsidiado", nit: "800140949", sispro: "EPSS03" },
  { valor: "CCF101", etiqueta: "CAJA COLOMBIANA DE SUBSIDIO FAMILIAR", regimen: "subsidiado", nit: "860007336", sispro: "CCF101" },
  { valor: "EPSS08", etiqueta: "CAJA COMPENSACIÓN FAMILIAR COMPENSAR", regimen: "subsidiado", nit: "860066942", sispro: "EPSS08" },
  { valor: "CCF015", etiqueta: "CAJA DE COMPENSACION FAMILIAR DE CORDOBA", regimen: "subsidiado", nit: "891080005", sispro: "CCF015" },
  { valor: "CCF023", etiqueta: "CAJA DE COMPENSACION FAMILIAR DE LA GUAJIRA", regimen: "subsidiado", nit: "892115006", sispro: "CCF023" },
  { valor: "CCFC20", etiqueta: "CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ", regimen: "subsidiado", nit: "891600091", sispro: "CCFC20" },
  { valor: "CCF045", etiqueta: "CAJA DE COMPENSACION FAMILIAR DEL NORTE DE SANTANDER- COMFANORTE A.R.S.", regimen: "subsidiado", nit: "890500516", sispro: "CCF045" },
  { valor: "CCF050", etiqueta: "CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO “COMFAORIENTE”", regimen: "contributivo", nit: "890500675", sispro: "CCF050" },
  { valor: "CCFS50", etiqueta: "CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO “COMFAORIENTE”", regimen: "subsidiado", nit: "890500675", sispro: "CCFS50" },
  { valor: "REUE04", etiqueta: "CAJA DE PREVISION SOCIAL DE LA UNIVERSIDAD DE CARTAGENA", regimen: "especial", nit: "806000509", sispro: "REUE04" },
  { valor: "REUE02", etiqueta: "CAJA DE PREVISIÓN SOCIAL DE LA UNIVERSIDAD INDUSTRIAL DE SANTANDER. CAPRUIS", regimen: "especial", nit: "890203183", sispro: "REUE02" },
  { valor: "CCF055", etiqueta: "CAJACOPI - CAJA DE COMPESACION FAMILIAR CAJACOPI ATLANTICO", regimen: "subsidiado", nit: "890102044", sispro: "CCF055" },
  { valor: "CCFS55", etiqueta: "CAJACOPI EPS SAS", regimen: "subsidiado", nit: "890102044", sispro: "CCFS55" },
  { valor: "EPSC34", etiqueta: "CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL REGIMEN SUBSIDIADO S.A.S.", regimen: "contributivo", nit: "900298372", sispro: "EPSC34" },
  { valor: "EPSS34", etiqueta: "CAPITAL SALUD EPS-S S.A.S.", regimen: "subsidiado", nit: "900298372", sispro: "EPSS34" },
  { valor: "EPS020", etiqueta: "CAPRECOM - CAJA DE PREVISION SOCIAL DE COMUNICACION CAPRECOM EPS", regimen: "subsidiado", nit: "899999026", sispro: "EPS020" },
  { valor: "EPSS25", etiqueta: "CAPRESOCA E.P.S.", regimen: "subsidiado", nit: "891856000", sispro: "EPSS25" },
  { valor: "EPS025", etiqueta: "CAPRESOCA EPS", regimen: "subsidiado", nit: "891856000", sispro: "EPS025" },
  { valor: "CCF009", etiqueta: "COMFABOY - CAJA DE COMPENSACION FAMILIAR DE BOYACA", regimen: "subsidiado", nit: "891800213", sispro: "CCF009" },
  { valor: "CCF102", etiqueta: "COMFACHOCO - CAJA DE COMPENSACION FAMILIAR DEL CHOCO", regimen: "subsidiado", nit: "891600091", sispro: "CCF102" },
  { valor: "CCF053", etiqueta: "COMFACUNDI - CAJA DE COMPENSACION FAMILIAR DE CUNDINAMAR", regimen: "subsidiado", nit: "860045904", sispro: "CCF053" },
  { valor: "CCF002", etiqueta: "COMFAMA CAJA DE COMPENSACIÓN FAMILIAR DE ANTIOQUIA", regimen: "subsidiado", nit: "8909008419", sispro: "CCF002" },
  { valor: "CCF007", etiqueta: "COMFAMILIAR - CAJA DE COMPENSACION FAMILIAR DE CARTAGENA", regimen: "subsidiado", nit: "890480110", sispro: "CCF007" },
  { valor: "CCF024", etiqueta: "COMFAMILIAR HUILA", regimen: "subsidiado", nit: "891180008", sispro: "CCF024" },
  { valor: "CCF049", etiqueta: "COMFAORIENTE - CAJA DE COMPENSACION FAMILIAR DEL ORIENTE COLOMBIANO", regimen: "subsidiado", nit: "890500675", sispro: "CCF049" },
  { valor: "CCF033", etiqueta: "COMFASUCRE EPS-S", regimen: "subsidiado", nit: "900048962", sispro: "CCF033" },
  { valor: "EPS012", etiqueta: "COMFENALCO VALLE EPS", regimen: "contributivo", nit: "890303093", sispro: "EPS012" },
  { valor: "EPSS12", etiqueta: "COMFENALCO VALLE EPS", regimen: "subsidiado", nit: "890303093", sispro: "EPSS12" },
  { valor: "ESS133", etiqueta: "COMPARTA - COOPERATIVA DE SALUD COMUNITARIA COMPARTA EPS S", regimen: "subsidiado", nit: "804002105", sispro: "ESS133" },
  { valor: "EPS008", etiqueta: "COMPENSAR", regimen: "contributivo", nit: "860066942", sispro: "EPS008" },
  { valor: "EPS022", etiqueta: "CONVIDA - ENTIDAD PROMOTORA DE SALUD DEL REGIMEN SUBSIDIADO EPSS CONVIDA", regimen: "subsidiado", nit: "899999107", sispro: "EPS022" },
  { valor: "EPS016", etiqueta: "COOMEVA EPS S A", regimen: "contributivo", nit: "805000427", sispro: "EPS016" },
  { valor: "ESSC24", etiqueta: "COOSALUD EPS S.A.", regimen: "contributivo", nit: "900226715", sispro: "ESSC24" },
  { valor: "ESSS24", etiqueta: "COOSALUD EPS S.A.", regimen: "subsidiado", nit: "900226715", sispro: "ESSS24" },
  { valor: "ESS024", etiqueta: "COOSALUD ESS EPS-S", regimen: "subsidiado", nit: "800249241", sispro: "ESS024" },
  { valor: "EPS023", etiqueta: "CRUZ BLANCA EPS", regimen: "contributivo", nit: "830009783", sispro: "EPS023" },
  { valor: "RES001", etiqueta: "DIRECCION DE SANIDAD POLICIA NACIONAL", regimen: "excepcion", nit: "830041314", sispro: "RES001" },
  { valor: "RES003", etiqueta: "DIRECCION GENERAL DE SANIDAD MILITAR", regimen: "excepcion", nit: "830039670", sispro: "RES003" },
  { valor: "EPSI01", etiqueta: "DUSAKAWI EPSI", regimen: "subsidiado", nit: "824001398", sispro: "EPSI01" },
  { valor: "ESS091", etiqueta: "ECOOPSOS - ENTIDAD COOPERATIVA SOLIDADARIA DE SALUD ECOOPSOS ESS EPS-S", regimen: "subsidiado", nit: "832000760", sispro: "ESS091" },
  { valor: "RES002", etiqueta: "ECOPETROL S.A.", regimen: "excepcion", nit: "899999068", sispro: "RES002" },
  { valor: "ESS002", etiqueta: "EMDISALUD - EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD EMDISALUD ESS-EPS-S", regimen: "subsidiado", nit: "811004055", sispro: "ESS002" },
  { valor: "ESS118", etiqueta: "EMSSANAR - ASOCIACION MUTIAL EMPRESA SOLIDARIA DE SALUD EMSSANAR ESS", regimen: "subsidiado", nit: "814000337", sispro: "ESS118" },
  { valor: "EPSS18", etiqueta: "ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.", regimen: "subsidiado", nit: "805001157", sispro: "EPSS18" },
  { valor: "CCF027", etiqueta: "EPS CAJA DE COMPENSACION FAMILIAR DE NARIÑO", regimen: "subsidiado", nit: "891280008", sispro: "CCF027" },
  { valor: "CCFC33", etiqueta: "EPS FAMILIAR DE COLOMBIA", regimen: "contributivo", nit: "901543761", sispro: "CCFC33" },
  { valor: "CCFS33", etiqueta: "EPS FAMILIAR DE COLOMBIA", regimen: "subsidiado", nit: "901543761", sispro: "CCFS33" },
  { valor: "EPS017", etiqueta: "EPS FAMISANAR LTDA", regimen: "contributivo", nit: "830003564", sispro: "EPS017" },
  { valor: "EPSS17", etiqueta: "EPS FAMISANAR S.A.S", regimen: "subsidiado", nit: "830003564", sispro: "EPSS17" },
  { valor: "EPS005", etiqueta: "EPS SANITAS", regimen: "contributivo", nit: "800251440", sispro: "EPS005" },
  { valor: "EPSS10", etiqueta: "EPS SURAMERICANA S.A.", regimen: "subsidiado", nit: "800088702", sispro: "EPSS10" },
  { valor: "RES004", etiqueta: "FIDUPREVISORA S.A", regimen: "excepcion", nit: "860525148", sispro: "RES004" },
  { valor: "REUE05", etiqueta: "FONDO DE SEGURIDAD SOCIAL EN SALUD UNIVERSIDAD DE NARIÑO", regimen: "especial", nit: "800118954", sispro: "REUE05" },
  { valor: "EAS027", etiqueta: "FONDO PASIVO SOCIAL FERROCARRILES NACIONALES DE COLOMBIA", regimen: "contributivo", nit: "800112806", sispro: "EAS027" },
  { valor: "EPS046", etiqueta: "FUNDACION SALUD MIA EPS", regimen: "contributivo", nit: "900914254", sispro: "EPS046" },
  { valor: "EPSS46", etiqueta: "FUNDACION SALUD MIA EPS", regimen: "subsidiado", nit: "900914254", sispro: "EPSS46" },
  { valor: "EPS039", etiqueta: "GOLDEN GROUP S.A. EPS", regimen: "contributivo", nit: "900074992", sispro: "EPS039" },
  { valor: "EPSI05", etiqueta: "MALLAMAS - EMPRESA PROMOTORA DE SALUD MALLAMAS EPS INDIGENA", regimen: "subsidiado", nit: "837000084", sispro: "EPSI05" },
  { valor: "EPSI02", etiqueta: "MANEXKA EPSI", regimen: "subsidiado", nit: "812002376", sispro: "EPSI02" },
  { valor: "EPS037", etiqueta: "NUEVA EPS", regimen: "contributivo", nit: "900156264", sispro: "EPS037" },
  { valor: "EPS041", etiqueta: "NUEVA EPS S.A.", regimen: "contributivo", nit: "900156264", sispro: "EPS041" },
  { valor: "EPSS37", etiqueta: "NUEVA EPS S.A.", regimen: "subsidiado", nit: "900156264", sispro: "EPSS37" },
  { valor: "EPSI06", etiqueta: "PIJAOS SALUD EPS -I", regimen: "subsidiado", nit: "809008362", sispro: "EPSI06" },
  { valor: "EPS002", etiqueta: "SALUD TOTAL - ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO", regimen: "contributivo", nit: "800130907", sispro: "EPS002" },
  { valor: "EPSS02", etiqueta: "SALUD TOTAL EPS-S S.A.", regimen: "subsidiado", nit: "800130907", sispro: "EPSS02" },
  { valor: "EPS033", etiqueta: "SALUD VIDA EPS", regimen: "contributivo", nit: "830074184", sispro: "EPS033" },
  { valor: "EPSS33", etiqueta: "SALUD VIDA EPS", regimen: "subsidiado", nit: "830074185", sispro: "EPSS33" },
  { valor: "EPS013", etiqueta: "SALUDCOOP EPS", regimen: "contributivo", nit: "800250119", sispro: "EPS013" },
  { valor: "EPST01", etiqueta: "SAVIA SALUD -ALIANZA MEDELLIN ANTIOQUIA EPS SAS", regimen: "subsidiado", nit: "900604350", sispro: "EPST01" },
  { valor: "EPS018", etiqueta: "SERVICIO OCCIDENTAL DE SALUD SA SOS", regimen: "contributivo", nit: "805001157", sispro: "EPS018" },
  { valor: "EPS010", etiqueta: "SURA - COMPANIA SURAMERICANA DE SERVICIOS DE SALUD SA", regimen: "contributivo", nit: "800088702", sispro: "EPS010" },
  { valor: "REUE99", etiqueta: "UISALUD UNIDAD ESPECIALIZADA DE SALUD DE LA UNIVERSIDAD INDUSTRIAL DE SANTANDER", regimen: "especial", nit: "890201213", sispro: "REUE99" },
  { valor: "REUE03", etiqueta: "UNIDAD ADMINISTRATIVA ESPECIAL DE SALUD UNIVERSIDAD DE CORDOBA", regimen: "especial", nit: "891080031", sispro: "REUE03" },
  { valor: "REUE09", etiqueta: "UNIDAD DE SALUD DE LA UNIVERSIDAD DEL ATLANTICO", regimen: "especial", nit: "802012036", sispro: "REUE09" },
  { valor: "RES014", etiqueta: "UNIDAD DE SERVICIOS DE SALUD UNISALUD - UPTC", regimen: "especial", nit: "891800330", sispro: "RES014" },
  { valor: "RES008", etiqueta: "UNIDAD DE SERVICIOS DE SALUD UNISALUD DE LA UNIVERSIDAD NACIONAL DE COLOMBIA", regimen: "especial", nit: "899999063", sispro: "RES008" },
  { valor: "EAS016", etiqueta: "UNIDAD SERVICIO MEDICO Y ODONTOLOGICO DE EMPRESAS PUBLICAS DE MEDELLIN EAS016", regimen: "contributivo", nit: "890904996", sispro: "EAS016" },
  { valor: "RES011", etiqueta: "UNIVERSIDAD DE ANTIOQUIA", regimen: "especial", nit: "890980040", sispro: "RES011" },
  { valor: "REUE06", etiqueta: "UNIVERSIDAD DEL CAUCA UNIDAD DE SALUD", regimen: "especial", nit: "891500319", sispro: "REUE06" },
  { valor: "RES007", etiqueta: "UNIVERSIDAD DEL VALLE SERVICIO DE SALUD", regimen: "especial", nit: "890399010", sispro: "RES007" }
];
