/* =========================================================================
   APS APP — SEED DE CATÁLOGOS
   GENERADO desde catalogos.js. No editar a mano: regenerar con bd/gen_seed.js.
   Archivo 2 de 3 — Datos de catálogo
   ========================================================================= */

BEGIN;

/* --- Parámetros de configuración (RN-003, RN-016, RN-022/023, RN-200) --- */
INSERT INTO cat.parametro (clave, valor, descripcion) VALUES
  ('departamento_fijo',  '{"codigo":"76","nombre":"Valle del Cauca"}', 'RN-003. Departamento fijado por despliegue.'),
  ('municipio_fijo',     '{"codigo":"76001","nombre":"Santiago de Cali"}', 'RN-005. Municipio fijado por despliegue.'),
  ('recuadro_municipal', '{"latMin":3.24,"latMax":3.56,"lonMin":-76.78,"lonMax":-76.40}', 'RN-022/023. Advierte sin bloquear fuera de rango.'),
  ('dias_maximos_ficha', '30', 'RN-016. Antigüedad máxima de la fecha de diligenciamiento.'),
  ('plazo_dias_prioridad','{"inmediata":2,"prioritaria":3,"regular":30}', 'RN-200/RN-226. Plazo máximo de respuesta por nivel.'),
  ('uzpe_predeterminada', '"UZPE006"', 'Valor prediligenciado del ítem 4.')
ON CONFLICT (clave) DO UPDATE SET valor = EXCLUDED.valor, actualizado_en = now();

/* --- DIVIPOLA (RN-003, RN-005) ----------------------------------------- */
INSERT INTO cat.departamento (codigo, nombre) VALUES ('76', 'Valle del Cauca')
  ON CONFLICT (codigo) DO NOTHING;
INSERT INTO cat.municipio (codigo, departamento_codigo, nombre)
  VALUES ('76001', '76', 'Santiago de Cali')
  ON CONFLICT (codigo) DO NOTHING;

/* --- País (RN-065) ------------------------------------------------------ */
INSERT INTO cat.pais (codigo, nombre) VALUES
  ('CO', 'Colombia'),
  ('VE', 'Venezuela'),
  ('EC', 'Ecuador'),
  ('PE', 'Perú'),
  ('HT', 'Haití'),
  ('CU', 'Cuba'),
  ('OT', 'Otra')
ON CONFLICT (codigo) DO NOTHING;

/* --- UZPE (RN-004) ------------------------------------------------------
   1 UZPE vigente(s). Para habilitar otra, márquela `vigente: true`
   en CAT_UZPE (catalogos.js) con su denominación oficial y regenere este archivo.
   El formulario lee la misma lista, así que ambos lados no pueden divergir.   */
INSERT INTO cat.uzpe (codigo, municipio_codigo, nombre, vigente) VALUES
  ('UZPE006', '76001', 'UZPE006', true)
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre, vigente = true;

/* --- EAPB (ítem 76, RN-076) ---------------------------------------------
   10 entidades. CONTENIDO PROVISIONAL: verificar contra el
   Registro Especial de EAPB del MSPS antes de cualquier despliegue.        */
INSERT INTO cat.eapb (codigo, nombre, regimen, vigente) VALUES
  ('EPS018', 'Servicio Occidental de Salud — SOS', 'contributivo', true),
  ('CCF050', 'Comfenalco Valle EPS', 'ambos', true),
  ('ESS024', 'Emssanar ESS', 'subsidiado', true),
  ('ESS062', 'Asmet Salud ESS', 'subsidiado', true),
  ('EPS037', 'Nueva EPS', 'ambos', true),
  ('EPS002', 'Salud Total EPS', 'ambos', true),
  ('EPS005', 'EPS Sanitas', 'ambos', true),
  ('EPS010', 'EPS Sura', 'contributivo', true),
  ('EPS017', 'Famisanar EPS', 'ambos', true),
  ('EPSI03', 'Asociación Indígena del Cauca — AIC', 'subsidiado', true)
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre, regimen = EXCLUDED.regimen, vigente = true;

/* --- Ocupaciones CIUO (ítem 73, RN-073) ---------------------------------
   16 ocupaciones. CONTENIDO PROVISIONAL: es una
   muestra de CIUO-08 A.C., no el catálogo del DANE. Cuando llegue completo
   conviene cargarlo como los CUPS (\copy) y no desde este archivo.          */
INSERT INTO cat.ocupacion_ciuo (codigo, nombre, riesgo_ocupacional) VALUES
  ('0000', 'Sin ocupación', NULL),
  ('2341', 'Docente de básica primaria', NULL),
  ('5120', 'Cocinero', NULL),
  ('5223', 'Vendedor de tienda o almacén', NULL),
  ('5321', 'Auxiliar de enfermería', 'biologico'),
  ('6111', 'Agricultor de cultivos transitorios', 'agroquimicos'),
  ('6113', 'Cultivador de caña de azúcar', 'agroquimicos'),
  ('7111', 'Constructor de vivienda', 'asbesto'),
  ('7126', 'Fontanero e instalador de tuberías', 'asbesto'),
  ('7233', 'Mecánico de vehículos', 'solventes'),
  ('8111', 'Minero', 'mineria'),
  ('8322', 'Conductor de automóvil, taxi o camioneta', NULL),
  ('9111', 'Trabajador doméstico', NULL),
  ('9520', 'Vendedor ambulante', NULL),
  ('9611', 'Recolector de residuos', 'residuos_peligrosos'),
  ('9999', 'Otra ocupación no clasificada', NULL)
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre, riesgo_ocupacional = EXCLUDED.riesgo_ocupacional;

/* --- Prestadores primarios (ítem 11, RN-011) ----------------------------
   5 prestadores de la red pública de Cali. Los códigos
   llevan prefijo PROV- a propósito: el REPS usa otro formato y no deben
   confundirse con códigos de habilitación reales.                          */
INSERT INTO cat.prestador (codigo, nombre, vigente) VALUES
  ('PROV-ESE-LADERA', 'E.S.E. Ladera', true),
  ('PROV-ESE-CENTRO', 'E.S.E. Centro', true),
  ('PROV-ESE-NORTE', 'E.S.E. Norte', true),
  ('PROV-ESE-ORIENTE', 'E.S.E. Oriente', true),
  ('PROV-ESE-SURORIENTE', 'E.S.E. Suroriente', true)
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre, vigente = true;

/* --- Territorios y microterritorios (RN-007, RN-008, Anexo A) -----------
   37 territorios: 30 rurales, 7 urbanos.
   El instrumento no asigna nombre propio al territorio: su código lo identifica. */
INSERT INTO cat.territorio (codigo, nombre, uzpe_codigo, es_rural) VALUES
  ('T48', 'T48', 'UZPE006', false),
  ('T49', 'T49', 'UZPE006', false),
  ('T50', 'T50', 'UZPE006', false),
  ('T51', 'T51', 'UZPE006', false),
  ('T52', 'T52', 'UZPE006', false),
  ('T53', 'T53', 'UZPE006', false),
  ('T54', 'T54', 'UZPE006', false),
  ('T55', 'T55', 'UZPE006', true),
  ('T56', 'T56', 'UZPE006', true),
  ('T57', 'T57', 'UZPE006', true),
  ('T58', 'T58', 'UZPE006', true),
  ('T59', 'T59', 'UZPE006', true),
  ('T60', 'T60', 'UZPE006', true),
  ('T61', 'T61', 'UZPE006', true),
  ('T62', 'T62', 'UZPE006', true),
  ('T63', 'T63', 'UZPE006', true),
  ('T64', 'T64', 'UZPE006', true),
  ('T65', 'T65', 'UZPE006', true),
  ('T66', 'T66', 'UZPE006', true),
  ('T67', 'T67', 'UZPE006', true),
  ('T68', 'T68', 'UZPE006', true),
  ('T69', 'T69', 'UZPE006', true),
  ('T70', 'T70', 'UZPE006', true),
  ('T71', 'T71', 'UZPE006', true),
  ('T72', 'T72', 'UZPE006', true),
  ('T73', 'T73', 'UZPE006', true),
  ('T74', 'T74', 'UZPE006', true),
  ('T75', 'T75', 'UZPE006', true),
  ('T76', 'T76', 'UZPE006', true),
  ('T77', 'T77', 'UZPE006', true),
  ('T78', 'T78', 'UZPE006', true),
  ('T79', 'T79', 'UZPE006', true),
  ('T80', 'T80', 'UZPE006', true),
  ('T81', 'T81', 'UZPE006', true),
  ('T82', 'T82', 'UZPE006', true),
  ('T83', 'T83', 'UZPE006', true),
  ('T84', 'T84', 'UZPE006', true)
ON CONFLICT (codigo) DO UPDATE
  SET es_rural = EXCLUDED.es_rural, uzpe_codigo = EXCLUDED.uzpe_codigo;

INSERT INTO cat.microterritorio (territorio_codigo, codigo, nombre, comuna) VALUES
  ('T48', 'MT01', 'San Cayetano', '3'),
  ('T48', 'MT02', 'Libertadores', '3'),
  ('T48', 'MT03', 'Nacional', '3'),
  ('T48', 'MT04', 'La Chanca', '3'),
  ('T49', 'MT01', 'Terrón Cabecera', '1'),
  ('T49', 'MT02', 'Malvinas', '1'),
  ('T49', 'MT03', 'Portada', '1'),
  ('T49', 'MT04', 'Palermo', '1'),
  ('T50', 'MT01', 'Legua', '1.1'),
  ('T50', 'MT02', 'Vista Hermosa', '1.1'),
  ('T50', 'MT03', 'Patio Bonito', '1.1'),
  ('T50', 'MT04', 'Aguacatal', '1.1'),
  ('T51', 'MT01', 'Los Comedores', '18'),
  ('T51', 'MT02', 'Cuatro Esquinas', '18'),
  ('T51', 'MT03', 'La Esperanza', '18'),
  ('T51', 'MT04', 'Cesoles', '18'),
  ('T52', 'MT01', 'Oasis', '18.1'),
  ('T52', 'MT02', 'Las Minas', '18.1'),
  ('T52', 'MT03', 'La Cañada', '18.1'),
  ('T52', 'MT04', 'La Piedra Brisas de la Chorrera', '18.1'),
  ('T53', 'MT01', 'Belèn', '20'),
  ('T53', 'MT02', 'Corea', '20'),
  ('T53', 'MT03', 'Siloé', '20'),
  ('T53', 'MT04', 'Quebrada Isabel Pérez', '20'),
  ('T54', 'MT01', 'Cortijo', '20.1'),
  ('T54', 'MT02', 'Lleras Camargo', '20.1'),
  ('T54', 'MT03', 'Brisas de Mayo', '20.1'),
  ('T54', 'MT04', 'Pueblo Joven', '20.1'),
  ('T55', 'MT01', 'Brisas de Montebello', 'Rural'),
  ('T55', 'MT02', 'Montecitos', 'Rural'),
  ('T55', 'MT03', 'Arrayanes', 'Rural'),
  ('T55', 'MT04', 'La Piscina', 'Rural'),
  ('T56', 'MT01', 'Colinas', 'Rural'),
  ('T56', 'MT02', 'Centro Puesto de Salud', 'Rural'),
  ('T56', 'MT03', 'Hora Cero', 'Rural'),
  ('T56', 'MT04', 'Las Guacas 107', 'Rural'),
  ('T57', 'MT01', 'Campo Alegre Cabecera', 'Rural'),
  ('T57', 'MT02', 'Campo Alegre Berlyn', 'Rural'),
  ('T57', 'MT03', 'Centro sector 4 y 5', 'Rural'),
  ('T57', 'MT04', 'Estadero Mi Rey', 'Rural'),
  ('T58', 'MT01', 'Cabecera', 'Rural'),
  ('T58', 'MT02', 'Normandía los Mangos', 'Rural'),
  ('T58', 'MT03', 'Normandía las Minas', 'Rural'),
  ('T58', 'MT04', 'El Filo', 'Rural'),
  ('T59', 'MT01', 'La María', 'Rural'),
  ('T59', 'MT02', 'La Fragua', 'Rural'),
  ('T59', 'MT03', 'Entre Ríos', 'Rural'),
  ('T59', 'MT04', 'San Isidro', 'Rural'),
  ('T60', 'MT01', 'Cabecera Alta', 'Rural'),
  ('T60', 'MT02', 'Vergel', 'Rural'),
  ('T60', 'MT03', 'Lomitas', 'Rural'),
  ('T60', 'MT04', 'Villa del Rosario', 'Rural'),
  ('T61', 'MT01', 'Cabecera Baja', 'Rural'),
  ('T61', 'MT02', 'Vista Hermosa', 'Rural'),
  ('T61', 'MT03', 'La Virgen', 'Rural'),
  ('T61', 'MT04', 'Tres Cruces', 'Rural'),
  ('T62', 'MT01', 'Las Palmas', 'Rural'),
  ('T62', 'MT02', 'Las Brisas', 'Rural'),
  ('T62', 'MT03', 'Las Victorias', 'Rural'),
  ('T62', 'MT04', 'Las Granjas', 'Rural'),
  ('T63', 'MT01', 'Montañitas parte Alta', 'Rural'),
  ('T63', 'MT02', 'El Filo', 'Rural'),
  ('T63', 'MT03', 'Los Limones', 'Rural'),
  ('T63', 'MT04', 'Montañitas parte Baja', 'Rural'),
  ('T64', 'MT01', 'Laureles', 'Rural'),
  ('T64', 'MT02', 'Alto Aguacatal Cabecera', 'Rural'),
  ('T64', 'MT03', 'El Silencio', 'Rural'),
  ('T64', 'MT04', 'Alto Aguacatal', 'Rural'),
  ('T65', 'MT01', 'Kilómetro 18', 'Rural'),
  ('T65', 'MT02', 'San Miguel Alto', 'Rural'),
  ('T65', 'MT03', 'San Miguel Bajo', 'Rural'),
  ('T65', 'MT04', 'Las Peñas', 'Rural'),
  ('T66', 'MT01', 'Cerezo', 'Rural'),
  ('T66', 'MT02', 'Palomar', 'Rural'),
  ('T66', 'MT03', 'San Miguel', 'Rural'),
  ('T66', 'MT04', 'Las Nieves Altas', 'Rural'),
  ('T67', 'MT01', 'San Pablo', 'Rural'),
  ('T67', 'MT02', 'San Antonio', 'Rural'),
  ('T67', 'MT03', 'Las Nieves Bajas', 'Rural'),
  ('T67', 'MT04', 'Cabecera', 'Rural'),
  ('T68', 'MT01', 'La Esperanza', 'Rural'),
  ('T68', 'MT02', 'La Ascensión', 'Rural'),
  ('T68', 'MT03', 'El Diamante', 'Rural'),
  ('T68', 'MT04', 'La Soledad', 'Rural'),
  ('T69', 'MT01', 'Cabecera', 'Rural'),
  ('T69', 'MT02', 'Las Nieves', 'Rural'),
  ('T69', 'MT03', 'Santa Elena Baja', 'Rural'),
  ('T69', 'MT04', 'Santa Elena Alta', 'Rural'),
  ('T70', 'MT01', 'Paujil parte Baja', 'Rural'),
  ('T70', 'MT02', 'Paujil parte Alta', 'Rural'),
  ('T70', 'MT03', 'Cabecera', 'Rural'),
  ('T70', 'MT04', 'El Bosque', 'Rural'),
  ('T71', 'MT01', 'El Porvenir', 'Rural'),
  ('T71', 'MT02', 'La Vega', 'Rural'),
  ('T71', 'MT03', 'Fincas los Sierra', 'Rural'),
  ('T71', 'MT04', 'El Pato', 'Rural'),
  ('T72', 'MT01', 'Loma de la Cajita', 'Rural'),
  ('T72', 'MT02', 'El Castillo', 'Rural'),
  ('T72', 'MT03', 'La Esmeralda', 'Rural'),
  ('T72', 'MT04', 'Cabecera', 'Rural'),
  ('T73', 'MT01', 'Peñas', 'Rural'),
  ('T73', 'MT02', 'Plan de Vivienda', 'Rural'),
  ('T73', 'MT03', 'Casa Blanca', 'Rural'),
  ('T73', 'MT04', 'Cabecera Baja Andes', 'Rural'),
  ('T74', 'MT01', 'Cabecera Alta', 'Rural'),
  ('T74', 'MT02', 'Yanaconas', 'Rural'),
  ('T74', 'MT03', 'La Emisora', 'Rural'),
  ('T74', 'MT04', 'Atenas', 'Rural'),
  ('T75', 'MT01', 'Los Cristales', 'Rural'),
  ('T75', 'MT02', 'Pueblo Nuevo', 'Rural'),
  ('T75', 'MT03', 'Quebrada Honda', 'Rural'),
  ('T75', 'MT04', 'La Reforma', 'Rural'),
  ('T76', 'MT01', 'Cabecera', 'Rural'),
  ('T76', 'MT02', 'El Otoño', 'Rural'),
  ('T76', 'MT03', 'Sirena - Sector Arrayanes', 'Rural'),
  ('T76', 'MT04', 'Sirena Santa Barbara', 'Rural'),
  ('T77', 'MT01', 'El Crucero Sector Alto', 'Rural'),
  ('T77', 'MT02', 'El Crucero Sector Bajo', 'Rural'),
  ('T77', 'MT03', 'El Rosario parte Alta', 'Rural'),
  ('T77', 'MT04', 'El Rosario parte Baja', 'Rural'),
  ('T78', 'MT01', 'Cabecera parte Baja', 'Rural'),
  ('T78', 'MT02', 'Cabecera Sector Oasis', 'Rural'),
  ('T78', 'MT03', 'Cabecera sector Areneros', 'Rural'),
  ('T78', 'MT04', 'Cabecera', 'Rural'),
  ('T79', 'MT01', 'Cascajal Sector Guayacal', 'Rural'),
  ('T79', 'MT02', 'Cascajal Sector Flamenco', 'Rural'),
  ('T79', 'MT03', 'Cauca Viejo', 'Rural'),
  ('T79', 'MT04', 'Cascajal Cabecera', 'Rural'),
  ('T80', 'MT01', 'La Pailita 1', 'Rural'),
  ('T80', 'MT02', 'Morgan', 'Rural'),
  ('T80', 'MT03', 'La Pailita 2', 'Rural'),
  ('T80', 'MT04', 'Morgan parte Alta', 'Rural'),
  ('T81', 'MT01', 'Cabecera', 'Rural'),
  ('T81', 'MT02', 'El Carmen', 'Rural'),
  ('T81', 'MT03', 'Sector Edén Alto', 'Rural'),
  ('T81', 'MT04', 'Sector Edén Bajo', 'Rural'),
  ('T82', 'MT01', 'Fonda', 'Rural'),
  ('T82', 'MT02', 'Fonda Sector la Rochela', 'Rural'),
  ('T82', 'MT03', 'Fonda Sector Bocatoma', 'Rural'),
  ('T82', 'MT04', 'Dosquebradas', 'Rural'),
  ('T83', 'MT01', 'La Cabecera', 'Rural'),
  ('T83', 'MT02', 'San Francisco', 'Rural'),
  ('T83', 'MT03', 'Alto San Pablo', 'Rural'),
  ('T83', 'MT04', 'Pico de Águila', 'Rural'),
  ('T84', 'MT01', 'San Pablo', 'Rural'),
  ('T84', 'MT02', 'La Vorágine', 'Rural'),
  ('T84', 'MT03', 'El Porvenir', 'Rural'),
  ('T84', 'MT04', 'Peón', 'Rural')
ON CONFLICT (territorio_codigo, codigo) DO UPDATE
  SET nombre = EXCLUDED.nombre, comuna = EXCLUDED.comuna;

/* --- Dominios de listas cerradas ---------------------------------------- */
INSERT INTO cat.dominio (codigo, nombre, item, regla, multiple) VALUES
  ('AREA_UBICACION', 'area ubicacion', 6, 'RN-006', false),
  ('TIPO_ID_RESPONSABLE', 'tipo id responsable', 12, 'RN-012', false),
  ('PERFIL_PROFESIONAL', 'perfil profesional', 14, 'RN-014', false),
  ('ENTORNO', 'entorno', 17, 'RN-017', false),
  ('SI_NO', 'si no', NULL, 'RN-001', false),
  ('SI_NO_NA', 'si no na', NULL, 'RN-037', false),
  ('SITUACION_INMINENTE', 'situacion inminente', 2, 'RN-002', false),
  ('ESTRATO', 'estrato', 27, 'RN-027', false),
  ('TIPO_VIVIENDA', 'tipo vivienda', 34, 'RN-034', false),
  ('MATERIAL_TECHO', 'material techo', 35, 'RN-035', false),
  ('RIESGOS_ACCIDENTE', 'riesgos accidente', 36, 'RN-036', true),
  ('FACTORES_CONTAMINACION', 'factores contaminacion', 38, 'RN-038', true),
  ('ANIMALES', 'animales', 40, 'RN-040', true),
  ('FUENTE_AGUA', 'fuente agua', 46, 'RN-046', false),
  ('DISPOSICION_EXCRETAS', 'disposicion excretas', 47, 'RN-047', false),
  ('AGUAS_RESIDUALES', 'aguas residuales', 48, 'RN-048', false),
  ('RESIDUOS_SOLIDOS', 'residuos solidos', 49, 'RN-049', false),
  ('TIPO_FAMILIA', 'tipo familia', 50, 'RN-050', false),
  ('ZARIT', 'zarit', 53, 'RN-053', false),
  ('SITUACIONES_RIESGO_FAMILIAR', 'situaciones riesgo familiar', 54, 'RN-054', true),
  ('PRACTICAS_VINCULO', 'practicas vinculo', 55, 'RN-055', true),
  ('REDES_APOYO', 'redes apoyo', 56, 'RN-056', false),
  ('PRACTICAS_CUIDADO_HOGAR', 'practicas cuidado hogar', 57, 'RN-057', true),
  ('TIPO_ID_INTEGRANTE', 'tipo id integrante', 62, 'RN-062', false),
  ('SEXO', 'sexo', 66, 'RN-066', false),
  ('GENERO', 'genero', 67, 'RN-067', false),
  ('AUTOIDENTIFICACION_GENERO', 'autoidentificacion genero', 68, 'RN-068', false),
  ('ORIENTACION_SEXUAL', 'orientacion sexual', 69, 'RN-069', false),
  ('ROL_FAMILIAR', 'rol familiar', 72, 'RN-072', false),
  ('NIVEL_EDUCATIVO', 'nivel educativo', 74, 'RN-074', false),
  ('REGIMEN_AFILIACION', 'regimen afiliacion', 75, 'RN-075', false),
  ('SUJETO_ESPECIAL_PROTECCION', 'sujeto especial proteccion', 77, 'RN-077', true),
  ('MODALIDAD_VIOLENCIA', 'modalidad violencia', 78, 'RN-078', true),
  ('PERTENENCIA_ETNICA', 'pertenencia etnica', 79, 'RN-079', false),
  ('SABERES_ANCESTRALES', 'saberes ancestrales', 81, 'RN-081', true),
  ('DISCAPACIDAD', 'discapacidad', 82, 'RN-082', true),
  ('PRACTICAS_CUIDADO', 'practicas cuidado', 86, 'RN-086', true),
  ('ATENCIONES_RPMS', 'atenciones rpms', 87, 'RN-087', true),
  ('ATENCIONES_MATERNO', 'atenciones materno', 88, 'RN-088', true),
  ('BARRERAS_ACCESO', 'barreras acceso', 89, 'RN-089', true),
  ('CONOCIMIENTO_DERECHO', 'conocimiento derecho', 90, 'RN-090', true),
  ('CLASIFICACION_ANTROPOMETRICA', 'clasificacion antropometrica', 96, 'RN-096', false),
  ('SIGNOS_DESNUTRICION', 'signos desnutricion', 97, 'RN-097', true),
  ('CLASIFICACION_TENSION', 'clasificacion tension', 99, 'RN-099', false),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'enfermedades no transmisibles', 100, 'RN-100', true),
  ('CONDICIONES_TRANSMISIBLES', 'condiciones transmisibles', 101, 'RN-101', true),
  ('ZONA_ENDEMICA', 'zona endemica', 102, 'RN-102', true),
  ('MOTIVO_NO_TRATAMIENTO', 'motivo no tratamiento', 104, 'RN-104', true),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'riesgos salud mental joven', 105, 'RN-105', true),
  ('SINTOMATOLOGIA_DEPRESIVA', 'sintomatologia depresiva', 106, 'RN-106', true),
  ('IDEACION_SUICIDA', 'ideacion suicida', 107, 'RN-107', false),
  ('TIPO_RESPUESTA', 'tipo respuesta', 115, 'RN-115', false),
  ('ESTADO_SEGUIMIENTO', 'estado seguimiento', 118, 'RN-226', false),
  ('TIPO_ID_EJECUTOR', 'tipo id ejecutor', 113, 'RN-113', false)
ON CONFLICT (codigo) DO NOTHING;

/* --- Opciones ----------------------------------------------------------- */
INSERT INTO cat.opcion (dominio_codigo, codigo, etiqueta, orden, es_excluyente, exige_texto, metadata) VALUES
  ('AREA_UBICACION', 'urbana', 'Área Urbana', 1, false, false, NULL),
  ('AREA_UBICACION', 'rural', 'Área rural', 2, false, false, NULL),
  ('AREA_UBICACION', 'centro_poblado', 'Centro poblado', 3, false, false, NULL),
  ('TIPO_ID_RESPONSABLE', 'CC', 'CC. Cédula de Ciudadanía', 1, false, false, NULL),
  ('TIPO_ID_RESPONSABLE', 'CD', 'CD. Carné Diplomático', 2, false, false, NULL),
  ('TIPO_ID_RESPONSABLE', 'CE', 'CE. Cédula de Extranjería', 3, false, false, NULL),
  ('TIPO_ID_RESPONSABLE', 'PT', 'PT. Permiso por Protección Temporal', 4, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'medicina', 'Medicina', 1, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'enfermeria', 'Enfermería (profesional)', 2, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'auxiliar_enfermeria', 'Auxiliar de enfermería', 3, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'psicologia', 'Psicología', 4, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'trabajo_social', 'Trabajo social', 5, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'odontologia', 'Odontología', 6, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'nutricion', 'Nutrición y dietética', 7, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'fisioterapia', 'Fisioterapia', 8, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'terapia_ocupacional', 'Terapia ocupacional', 9, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'gestor_comunitario', 'Gestor / Promotor comunitario en salud', 10, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'tecnico_saneamiento', 'Técnico en salud pública / saneamiento ambiental', 11, false, false, NULL),
  ('PERFIL_PROFESIONAL', 'otro', 'Otro', 12, false, true, NULL),
  ('ENTORNO', 'hogar', 'Hogar', 1, false, false, NULL),
  ('ENTORNO', 'comunitario', 'Comunitario', 2, false, false, NULL),
  ('ENTORNO', 'institucional', 'Institucional', 3, false, false, NULL),
  ('ENTORNO', 'educativo', 'Educativo', 4, false, false, NULL),
  ('ENTORNO', 'laboral', 'Laboral', 5, false, false, NULL),
  ('SI_NO', 'si', 'Sí', 1, false, false, NULL),
  ('SI_NO', 'no', 'No', 2, false, false, NULL),
  ('SI_NO_NA', 'si', 'Sí', 1, false, false, NULL),
  ('SI_NO_NA', 'no', 'No', 2, false, false, NULL),
  ('SI_NO_NA', 'no_aplica', 'No aplica', 3, true, false, NULL),
  ('SITUACION_INMINENTE', 'fisica', 'Física (urgencia vital)', 1, false, false, '{"prioritaria":true}'::jsonb),
  ('SITUACION_INMINENTE', 'psicologica', 'Psicológica (urgencia vital en salud mental)', 2, false, false, '{"prioritaria":true}'::jsonb),
  ('SITUACION_INMINENTE', 'emergencia', 'Situación de emergencia o desastre', 3, false, false, '{"prioritaria":true}'::jsonb),
  ('SITUACION_INMINENTE', 'no_aplica', 'No aplica', 4, true, false, '{"prioritaria":false}'::jsonb),
  ('ESTRATO', 'bajo_bajo', 'Bajo - Bajo', 1, false, false, NULL),
  ('ESTRATO', 'bajo', 'Bajo', 2, false, false, NULL),
  ('ESTRATO', 'medio_bajo', 'Medio - Bajo', 3, false, false, NULL),
  ('ESTRATO', 'medio', 'Medio', 4, false, false, NULL),
  ('ESTRATO', 'medio_alto', 'Medio - Alto', 5, false, false, NULL),
  ('ESTRATO', 'alto', 'Alto', 6, false, false, NULL),
  ('TIPO_VIVIENDA', 'casa', 'Casa', 1, false, false, NULL),
  ('TIPO_VIVIENDA', 'apartamento', 'Apartamento', 2, false, false, NULL),
  ('TIPO_VIVIENDA', 'cuarto', 'Tipo "Cuarto"', 3, false, false, NULL),
  ('TIPO_VIVIENDA', 'tradicional_indigena', 'Vivienda tradicional Indígena', 4, false, false, NULL),
  ('TIPO_VIVIENDA', 'carpa', 'Carpa', 5, false, false, NULL),
  ('TIPO_VIVIENDA', 'tradicional_etnica', 'Vivienda tradicional étnica', 6, false, false, NULL),
  ('TIPO_VIVIENDA', 'contenedor', 'Contenedor', 7, false, false, NULL),
  ('TIPO_VIVIENDA', 'embarcacion', 'Embarcación', 8, false, false, NULL),
  ('TIPO_VIVIENDA', 'vagon', 'Vagón', 9, false, false, NULL),
  ('TIPO_VIVIENDA', 'refugio_natural', 'Refugio Natural', 10, false, false, NULL),
  ('TIPO_VIVIENDA', 'cueva', 'Cueva', 11, false, false, NULL),
  ('TIPO_VIVIENDA', 'puente', 'Puente', 12, false, false, NULL),
  ('MATERIAL_TECHO', 'concreto', 'Concreto', 1, false, false, NULL),
  ('MATERIAL_TECHO', 'tejas_barro', 'Tejas de barro', 2, false, false, NULL),
  ('MATERIAL_TECHO', 'fibrocemento_sin_asbesto', 'Fibrocemento sin asbesto', 3, false, false, NULL),
  ('MATERIAL_TECHO', 'zinc', 'Zinc', 4, false, false, NULL),
  ('MATERIAL_TECHO', 'plastico', 'Plástico', 5, false, false, NULL),
  ('MATERIAL_TECHO', 'fibrocemento_con_asbesto', 'Teja o lámina de fibrocemento con asbesto', 6, false, false, NULL),
  ('MATERIAL_TECHO', 'palma_paja', 'Palma o paja', 7, false, false, NULL),
  ('MATERIAL_TECHO', 'desechos', 'Desechos (cartón, lata, etc.)', 8, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'objetos_cortopunzantes', 'Objetos cortantes o punzantes al alcance de los niños', 1, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'sustancias_quimicas', 'Sustancias químicas al alcance de los niños y/o reenvasadas en envases de alimentos o bebidas', 2, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'medicamentos', 'Medicamentos al alcance de los niños', 3, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'velas_encendidas', 'Velas, velones, incienso encendidos en la vivienda', 4, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'conexiones_electricas', 'Conexiones eléctricas en mal estado o sobrecargadas', 5, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'objetos_pequenos', 'Botones, canicas entre otros objetos pequeños o con piezas que puedan desmontarse, al alcance de los niños', 6, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'pasillos_obstruidos', 'Pasillos obstruidos con juguetes, sillas u otros objetos', 7, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'superficies_resbaladizas', 'Superficies resbaladizas, suelos con agua, grasas, aceites, entre otros', 8, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'tanques_sin_tapa', 'Tanques o recipientes de almacenamiento de agua sin tapa', 9, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'escaleras_sin_proteccion', 'Escaleras sin protección', 10, false, false, NULL),
  ('RIESGOS_ACCIDENTE', 'ninguno', 'Ninguno', 11, true, false, '{"excluyente":true}'::jsonb),
  ('FACTORES_CONTAMINACION', 'cultivos', 'Cultivos', 1, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'apriscos', 'Apriscos', 2, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'porquerizas', 'Porquerizas', 3, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'galpones', 'Galpones', 4, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'terrenos_baldios', 'Terrenos baldíos', 5, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'plagas', 'Presencia de Plagas: roedores, cucarachas, zancudos, moscas, etc.', 6, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'malos_olores', 'Malos olores', 7, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'ruido', 'Ruido o sonidos desagradables', 8, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'excretas_satelite', 'Sitios satélites de disposición de excretas', 9, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'rellenos_botaderos', 'Rellenos sanitarios / botaderos', 10, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'contaminacion_visual', 'Contaminación visual', 11, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'rio_quebrada', 'Río o quebrada', 12, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'ptar', 'Planta de tratamiento de agua residual', 13, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'extraccion_minera', 'Extracción minera', 14, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'industrias_contaminantes', 'Industrias contaminantes (del sector energético, minero, transporte, construcción, manufacturera, entre otros)', 15, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'canales_agua_lluvia', 'Canales de agua lluvia', 16, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'trafico_vehicular', 'Vías de alto tráfico vehicular', 17, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'quemas_cielo_abierto', 'Quemas a cielo abierto', 18, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'alta_tension', 'Fuentes de energía eléctrica de alta tensión', 19, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'agroquimicos', 'Aspersión o almacenamiento de agroquímicos u otras sustancias químicas', 20, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'asbesto', 'Industrias de construcción, demolición, talleres u otros que usen o dispongan de material de asbesto', 21, false, false, NULL),
  ('FACTORES_CONTAMINACION', 'ninguno', 'Ninguno', 22, true, false, '{"excluyente":true}'::jsonb),
  ('ANIMALES', 'perros', 'Perros', 1, false, false, NULL),
  ('ANIMALES', 'gatos', 'Gatos', 2, false, false, NULL),
  ('ANIMALES', 'porcinos', 'Porcinos', 3, false, false, NULL),
  ('ANIMALES', 'bovinos', 'Bovinos: Búfalos, vacas, toros', 4, false, false, NULL),
  ('ANIMALES', 'equinos', 'Equinos: Asnos, mulas, caballos, burros', 5, false, false, NULL),
  ('ANIMALES', 'ovinos_caprinos', 'Ovinos / caprino', 6, false, false, NULL),
  ('ANIMALES', 'aves_produccion', 'Aves de producción', 7, false, false, NULL),
  ('ANIMALES', 'aves_ornamentales', 'Aves ornamentales', 8, false, false, NULL),
  ('ANIMALES', 'peces_hamster', 'Peces ornamentales, hámster', 9, false, false, NULL),
  ('ANIMALES', 'cobayos_conejos', 'Cobayos, conejos', 10, false, false, NULL),
  ('ANIMALES', 'silvestres', 'Animales silvestres', 11, false, false, NULL),
  ('ANIMALES', 'otro', 'Otro', 12, false, true, NULL),
  ('ANIMALES', 'ninguno', 'Ninguno', 13, true, false, '{"excluyente":true}'::jsonb),
  ('FUENTE_AGUA', 'acueducto_esp', 'Acueducto administrado por empresa prestadora (ESP)', 1, false, false, '{"noSegura":false}'::jsonb),
  ('FUENTE_AGUA', 'acueducto_veredal', 'Acueducto veredal o comunitario', 2, false, false, '{"noSegura":false}'::jsonb),
  ('FUENTE_AGUA', 'pila_publica', 'Pila pública', 3, false, false, '{"noSegura":false}'::jsonb),
  ('FUENTE_AGUA', 'agua_embotellada', 'Agua embotellada o en bolsa', 4, false, false, '{"noSegura":false}'::jsonb),
  ('FUENTE_AGUA', 'carro_tanque', 'Carro tanque', 5, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'distribucion_comunitaria', 'Abasto con distribución comunitaria', 6, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'pozo_con_bomba', 'Pozo con bomba', 7, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'pozo_sin_bomba', 'Pozo sin bomba, aljibe, jagüey o barreno', 8, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'laguna_jaguey', 'Laguna o jagüey', 9, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'rio_quebrada', 'Río, quebrada', 10, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'manantial', 'Manantial o nacimiento', 11, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'aguas_lluvias', 'Aguas lluvias', 12, false, false, '{"noSegura":true}'::jsonb),
  ('FUENTE_AGUA', 'aguatero', 'Aguatero', 13, false, false, '{"noSegura":true}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'alcantarillado', 'Sanitario conectado al alcantarillado', 1, false, false, '{"critica":false}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'letrina', 'Sanitario y letrina', 2, false, false, '{"critica":false}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'pozo_septico', 'Sanitario conectado a pozo séptico', 3, false, false, '{"critica":false}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'ecologico_seco', 'Sanitario ecológico seco', 4, false, false, '{"critica":false}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'sin_conexion', 'Sanitario sin conexión', 5, false, false, '{"critica":true}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'fuente_hidrica', 'Sanitario con disposición a fuente hídrica', 6, false, false, '{"critica":true}'::jsonb),
  ('DISPOSICION_EXCRETAS', 'campo_abierto', 'Campo abierto', 7, false, false, '{"critica":true}'::jsonb),
  ('AGUAS_RESIDUALES', 'alcantarillado', 'Alcantarillado', 1, false, false, '{"critica":false}'::jsonb),
  ('AGUAS_RESIDUALES', 'pozo_septico', 'Pozo séptico', 2, false, false, '{"critica":false}'::jsonb),
  ('AGUAS_RESIDUALES', 'campo_oxidacion', 'Campo de oxidación', 3, false, false, '{"critica":false}'::jsonb),
  ('AGUAS_RESIDUALES', 'biofiltro', 'Biofiltro', 4, false, false, '{"critica":false}'::jsonb),
  ('AGUAS_RESIDUALES', 'fuente_hidrica', 'Fuente hídrica', 5, false, false, '{"critica":true}'::jsonb),
  ('AGUAS_RESIDUALES', 'campo_abierto', 'Campo abierto', 6, false, false, '{"critica":true}'::jsonb),
  ('RESIDUOS_SOLIDOS', 'servicio_aseo', 'Recolección por parte del servicio de aseo distrital o municipal', 1, false, false, '{"critica":false}'::jsonb),
  ('RESIDUOS_SOLIDOS', 'enterramiento', 'Enterramiento', 2, false, false, '{"critica":true}'::jsonb),
  ('RESIDUOS_SOLIDOS', 'quema', 'Quema a campo abierto', 3, false, false, '{"critica":true}'::jsonb),
  ('RESIDUOS_SOLIDOS', 'fuentes_agua', 'Disposición en fuentes de agua cercana', 4, false, false, '{"critica":true}'::jsonb),
  ('RESIDUOS_SOLIDOS', 'campo_abierto', 'Disposición a campo abierto', 5, false, false, '{"critica":true}'::jsonb),
  ('TIPO_FAMILIA', 'nuclear_biparental', 'Nuclear biparental', 1, false, false, NULL),
  ('TIPO_FAMILIA', 'nuclear_monoparental', 'Nuclear monoparental', 2, false, false, NULL),
  ('TIPO_FAMILIA', 'extenso_biparental', 'Extenso biparental', 3, false, false, NULL),
  ('TIPO_FAMILIA', 'extenso_monoparental', 'Extenso monoparental', 4, false, false, NULL),
  ('TIPO_FAMILIA', 'compuesto_biparental', 'Compuesto biparental', 5, false, false, NULL),
  ('TIPO_FAMILIA', 'compuesto_monoparental', 'Compuesto monoparental', 6, false, false, NULL),
  ('TIPO_FAMILIA', 'unipersonal', 'Unipersonal', 7, false, false, NULL),
  ('ZARIT', 'ausencia', 'Ausencia de sobrecarga (≤ 46)', 1, false, false, '{"prioridad":null}'::jsonb),
  ('ZARIT', 'ligera', 'Sobrecarga ligera (47-55)', 2, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZARIT', 'intensa', 'Sobrecarga intensa (≥ 56)', 3, false, false, '{"prioridad":"prioritaria"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'inicio_convivencia', 'Inicio de la convivencia en pareja', 1, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'nuevo_integrante', 'Llegada de un nuevo integrante', 2, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'ingreso_estudiar', 'Ingreso a estudiar', 3, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'perdida_ano_escolar', 'Pérdida del año escolar', 4, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'embarazo_adolescente', 'Embarazo temprano o adolescente', 5, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'independencia_hijos', 'Independencia de los hijos-hijas', 6, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'separacion', 'Separación', 7, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'jubilacion', 'Jubilación', 8, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'duelo', 'Duelo', 9, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'desempleo', 'Desempleo o pérdida abrupta del trabajo', 10, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'crisis_economica', 'Pérdidas o crisis económicas', 11, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'muerte_inesperada', 'Muerte inesperada', 12, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'migracion', 'Migración', 13, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'enfermedad_terminal', 'Enfermedad terminal o huérfana/rara en alguno de sus integrantes', 14, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'accidente_discapacidad', 'Accidente o situación que genera discapacidad', 15, false, false, NULL),
  ('SITUACIONES_RIESGO_FAMILIAR', 'antecedente_suicidio', 'Antecedentes de intento o muerte por suicidio en alguno de sus integrantes', 16, false, false, '{"riesgo":"suicidio"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'violencia', 'Vivencia de alguna forma de violencia', 17, false, false, '{"riesgo":"violencia"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'abandono', 'Persona en situación de abandono', 18, false, false, '{"riesgo":"abandono"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'consumo_spa', 'Consumo problemático de sustancias psicoactivas, incluyendo alcohol', 19, false, false, '{"riesgo":"spa"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'trastorno_mental', 'Trastorno de salud mental', 20, false, false, '{"riesgo":"salud_mental"}'::jsonb),
  ('SITUACIONES_RIESGO_FAMILIAR', 'ninguna', 'Ninguna', 21, true, false, '{"excluyente":true}'::jsonb),
  ('PRACTICAS_VINCULO', 'maneja_tension', 'Cuando hay tensión o estrés en la familia lo reconoce y encuentran la forma de manejarlas de manera pacífica', 1, false, false, NULL),
  ('PRACTICAS_VINCULO', 'decisiones_concertadas', 'Las decisiones familiares son concertadas teniendo en cuenta a todos sus integrantes', 2, false, false, NULL),
  ('PRACTICAS_VINCULO', 'resuelve_conflictos', 'La familia resuelve los conflictos buscando el bienestar de todos sus integrantes', 3, false, false, NULL),
  ('PRACTICAS_VINCULO', 'escucha_activa', 'La comunicación en la familia está basada en la escucha activa, el respeto y la negociación', 4, false, false, NULL),
  ('PRACTICAS_VINCULO', 'acompana_menores', 'Los padres y cuidadores comparten, apoyan y supervisan las actividades de niños y adolescentes con respeto y límites', 5, false, false, NULL),
  ('PRACTICAS_VINCULO', 'considera_mayores', 'Los integrantes tienen en cuenta los intereses, opiniones y preferencias de las personas adultas mayores', 6, false, false, NULL),
  ('REDES_APOYO', 'cuenta_protectoras', 'Cuenta con redes de apoyo sociales protectoras para el cuidado de su salud', 1, false, false, '{"riesgo":false}'::jsonb),
  ('REDES_APOYO', 'cuenta_ampliables', 'Cuenta con redes de apoyo sociales para el cuidado de su salud, pero podría ampliarlas para fortalecerse', 2, false, false, '{"riesgo":false}'::jsonb),
  ('REDES_APOYO', 'no_cuenta', 'No identifica / no cuenta con redes de apoyo sociales protectoras', 3, false, false, '{"riesgo":true}'::jsonb),
  ('PRACTICAS_CUIDADO_HOGAR', 'tratamiento_agua', 'Tratamiento casero al agua antes del consumo humano y almacenamiento adecuado', 1, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'ventilacion', 'Facilita la circulación del aire en la vivienda a través de la ventilación natural o artificial', 2, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'evita_humo', 'Evita el consumo de tabaco, el encendido de carros al interior de la vivienda y el uso de leña para cocinar', 3, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'residuos_tapados', 'Los residuos sólidos se almacenan en recipientes con tapa, se separan en la fuente, no se queman, no se tiran a campo abierto o en fuentes de agua', 4, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'pisos_limpios', 'Los pisos y paredes de la vivienda están limpios', 5, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'toldillos', 'Usa toldillos, angeos y trampas caseras para la protección contra vectores y roedores', 6, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'peridomicilio_limpio', 'Al interior de la vivienda o el peri-domicilio, jardín o espacios como patio o azotea están limpios', 7, false, false, NULL),
  ('PRACTICAS_CUIDADO_HOGAR', 'quimicos_seguros', 'El lugar donde se almacenan los productos químicos está ventilado, cerrado, separado de alimentos y fuera del alcance de niños y mascotas', 8, false, false, NULL),
  ('TIPO_ID_INTEGRANTE', 'AS', 'AS. Adulto sin Identificación', 1, false, false, '{"formato":"temporal","edadMinMeses":216,"edadMaxMeses":null,"bloqueaEdad":true,"exigeExtranjero":false,"sinDocumento":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'CC', 'CC. Cédula de Ciudadanía', 2, false, false, '{"formato":"numerico_6_10","edadMinMeses":216,"edadMaxMeses":null,"bloqueaEdad":false,"exigeExtranjero":false}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'CD', 'CD. Carné Diplomático', 3, false, false, '{"formato":"alfanumerico_5_16","edadMinMeses":null,"edadMaxMeses":null,"bloqueaEdad":false,"exigeExtranjero":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'CE', 'CE. Cédula de Extranjería', 4, false, false, '{"formato":"alfanumerico_5_16","edadMinMeses":null,"edadMaxMeses":null,"bloqueaEdad":false,"exigeExtranjero":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'MS', 'MS. Menor sin Identificación', 5, false, false, '{"formato":"temporal","edadMinMeses":0,"edadMaxMeses":215,"bloqueaEdad":true,"exigeExtranjero":false,"sinDocumento":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'NV', 'NV. Certificado de Nacido Vivo', 6, false, false, '{"formato":"alfanumerico_5_16","edadMinMeses":0,"edadMaxMeses":11,"bloqueaEdad":false,"exigeExtranjero":false}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'PE', 'PE. Permiso Especial de Permanencia', 7, false, false, '{"formato":"alfanumerico_5_16","edadMinMeses":null,"edadMaxMeses":null,"bloqueaEdad":false,"exigeExtranjero":true,"migrante":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'PT', 'PT. Permiso por Protección Temporal', 8, false, false, '{"formato":"alfanumerico_5_16","edadMinMeses":null,"edadMaxMeses":null,"bloqueaEdad":false,"exigeExtranjero":true,"migrante":true}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'RC', 'RC. Registro Civil', 9, false, false, '{"formato":"numerico_8_11","edadMinMeses":0,"edadMaxMeses":83,"bloqueaEdad":false,"exigeExtranjero":false}'::jsonb),
  ('TIPO_ID_INTEGRANTE', 'TI', 'TI. Tarjeta de identidad', 10, false, false, '{"formato":"numerico_6_10","edadMinMeses":84,"edadMaxMeses":215,"bloqueaEdad":false,"exigeExtranjero":false}'::jsonb),
  ('SEXO', 'hombre', 'Hombre', 1, false, false, NULL),
  ('SEXO', 'mujer', 'Mujer', 2, false, false, NULL),
  ('SEXO', 'intersexual', 'Intersexual (Indeterminado)', 3, false, false, NULL),
  ('GENERO', 'femenino', 'Femenino', 1, false, false, NULL),
  ('GENERO', 'masculino', 'Masculino', 2, false, false, NULL),
  ('AUTOIDENTIFICACION_GENERO', 'femenino', 'Femenino', 1, false, false, NULL),
  ('AUTOIDENTIFICACION_GENERO', 'masculino', 'Masculino', 2, false, false, NULL),
  ('AUTOIDENTIFICACION_GENERO', 'transexual', 'Transexual', 3, false, false, '{"diversa":true}'::jsonb),
  ('AUTOIDENTIFICACION_GENERO', 'transgenero', 'Transgenero', 4, false, false, '{"diversa":true}'::jsonb),
  ('AUTOIDENTIFICACION_GENERO', 'no_responde', 'No responde', 5, false, false, NULL),
  ('AUTOIDENTIFICACION_GENERO', 'otro', 'Otro', 6, false, true, '{"exigeCual":true}'::jsonb),
  ('ORIENTACION_SEXUAL', 'heterosexual', 'Heterosexual', 1, false, false, NULL),
  ('ORIENTACION_SEXUAL', 'lesbiana', 'Lesbiana', 2, false, false, NULL),
  ('ORIENTACION_SEXUAL', 'gay', 'Gay', 3, false, false, NULL),
  ('ORIENTACION_SEXUAL', 'bisexual', 'Bisexual', 4, false, false, NULL),
  ('ORIENTACION_SEXUAL', 'no_responde', 'No responde', 5, false, false, NULL),
  ('ORIENTACION_SEXUAL', 'otro', 'Otro', 6, false, true, '{"exigeCual":true}'::jsonb),
  ('ROL_FAMILIAR', 'responsable_economico', 'Responsable económico de la familia', 1, false, false, NULL),
  ('ROL_FAMILIAR', 'conyuge', 'Cónyuge o compañero(a)', 2, false, false, NULL),
  ('ROL_FAMILIAR', 'hijo', 'Hijo(a)', 3, false, false, NULL),
  ('ROL_FAMILIAR', 'hermano', 'Hermano(a)', 4, false, false, NULL),
  ('ROL_FAMILIAR', 'padre_madre', 'Padre o madre', 5, false, false, NULL),
  ('ROL_FAMILIAR', 'otros', 'Otros', 6, false, true, NULL),
  ('NIVEL_EDUCATIVO', 'preescolar', 'Preescolar', 1, false, false, '{"edadMinimaEsperada":3}'::jsonb),
  ('NIVEL_EDUCATIVO', 'basica_primaria', 'Básica Primaria', 2, false, false, '{"edadMinimaEsperada":5}'::jsonb),
  ('NIVEL_EDUCATIVO', 'basica_secundaria', 'Básica Secundaria', 3, false, false, '{"edadMinimaEsperada":10}'::jsonb),
  ('NIVEL_EDUCATIVO', 'media_academica', 'Media Académica o Clásica', 4, false, false, '{"edadMinimaEsperada":14}'::jsonb),
  ('NIVEL_EDUCATIVO', 'media_tecnica', 'Media Técnica (Bachillerato Técnico)', 5, false, false, '{"edadMinimaEsperada":14}'::jsonb),
  ('NIVEL_EDUCATIVO', 'normalista', 'Normalista', 6, false, false, '{"edadMinimaEsperada":16}'::jsonb),
  ('NIVEL_EDUCATIVO', 'tecnica_profesional', 'Técnica Profesional', 7, false, false, '{"edadMinimaEsperada":16}'::jsonb),
  ('NIVEL_EDUCATIVO', 'tecnologica', 'Tecnológica', 8, false, false, '{"edadMinimaEsperada":17}'::jsonb),
  ('NIVEL_EDUCATIVO', 'profesional', 'Profesional', 9, false, false, '{"edadMinimaEsperada":20}'::jsonb),
  ('NIVEL_EDUCATIVO', 'especializacion', 'Especialización', 10, false, false, '{"edadMinimaEsperada":22}'::jsonb),
  ('NIVEL_EDUCATIVO', 'maestria', 'Maestría', 11, false, false, '{"edadMinimaEsperada":23}'::jsonb),
  ('NIVEL_EDUCATIVO', 'doctorado', 'Doctorado', 12, false, false, '{"edadMinimaEsperada":24}'::jsonb),
  ('NIVEL_EDUCATIVO', 'tecnica_laboral', 'Técnica Laboral', 13, false, false, '{"edadMinimaEsperada":15}'::jsonb),
  ('NIVEL_EDUCATIVO', 'ninguno', 'Ninguno', 14, true, false, '{"edadMinimaEsperada":0}'::jsonb),
  ('REGIMEN_AFILIACION', 'subsidiado', 'Subsidiado', 1, false, false, NULL),
  ('REGIMEN_AFILIACION', 'contributivo', 'Contributivo', 2, false, false, NULL),
  ('REGIMEN_AFILIACION', 'especial', 'Especial', 3, false, false, NULL),
  ('REGIMEN_AFILIACION', 'excepcion', 'Excepción', 4, false, false, NULL),
  ('REGIMEN_AFILIACION', 'no_afiliado', 'No afiliado', 5, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'ninez', 'Niñas, niños o adolescentes', 1, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'gestante', 'Gestante', 2, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'adulto_mayor', 'Persona adulta mayor', 3, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'orientacion_diversa', 'Personas con orientación sexual diversa', 4, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'campesino', 'Campesina o campesino', 5, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'migrante', 'Migrantes', 6, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'madre_cabeza_familia', 'Madre cabeza de familia', 7, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'enfermedad_huerfana', 'Personas con enfermedades huérfanas', 8, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'victima_conflicto', 'Víctima del conflicto armado', 9, false, false, '{"violencia":true}'::jsonb),
  ('SUJETO_ESPECIAL_PROTECCION', 'victima_violencia_genero', 'Víctima de violencia de género e intrafamiliar', 10, false, false, '{"violencia":true}'::jsonb),
  ('SUJETO_ESPECIAL_PROTECCION', 'victima_violencia_interpersonal', 'Víctima de violencia interpersonal', 11, false, false, '{"violencia":true}'::jsonb),
  ('SUJETO_ESPECIAL_PROTECCION', 'privado_libertad', 'Persona privada de la libertad (medida domiciliaria)', 12, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'responsabilidad_penal_adolescente', 'Personas en el sistema de responsabilidad penal adolescente', 13, false, false, NULL),
  ('SUJETO_ESPECIAL_PROTECCION', 'otro', 'Otro', 14, false, true, '{"exigeCual":true}'::jsonb),
  ('SUJETO_ESPECIAL_PROTECCION', 'ninguna', 'Ninguna', 15, true, false, '{"excluyente":true}'::jsonb),
  ('MODALIDAD_VIOLENCIA', 'fisica', 'Física', 1, false, false, NULL),
  ('MODALIDAD_VIOLENCIA', 'psicologica', 'Psicológica', 2, false, false, NULL),
  ('MODALIDAD_VIOLENCIA', 'negligencia_abandono', 'Negligencia y abandono', 3, false, false, NULL),
  ('MODALIDAD_VIOLENCIA', 'sexual', 'Sexual', 4, false, false, NULL),
  ('MODALIDAD_VIOLENCIA', 'patrimonial', 'Patrimonial o económica', 5, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'indigena', 'Indígena', 1, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'rrom', 'Rrom (Gitanos)', 2, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'negro', 'Negro', 3, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'afrocolombiano', 'Afrocolombiano', 4, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'raizal', 'Raizal (San Andrés y Providencia)', 5, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'palenquero', 'Palenquero de San Basilio de Palenque', 6, false, false, NULL),
  ('PERTENENCIA_ETNICA', 'ninguna', 'Ninguna', 7, true, false, NULL),
  ('SABERES_ANCESTRALES', 'proteccion_danos', 'Prácticas para proteger ante posibles daños (aseguranzas, rituales y otros)', 1, false, false, NULL),
  ('SABERES_ANCESTRALES', 'transicion', 'Prácticas que acompañan en momentos de transición (arrullos o cantos, rituales de paso u otros)', 2, false, false, NULL),
  ('SABERES_ANCESTRALES', 'cuidado_salud', 'Prácticas tradicionales para el cuidado de la salud (baile o danza, música, uso de plantas, masajes u otros)', 3, false, false, NULL),
  ('SABERES_ANCESTRALES', 'armonizacion', 'Prácticas de armonización o para favorecer el bienestar (rituales, consejería del sabedor/a, pagamentos)', 4, false, false, NULL),
  ('SABERES_ANCESTRALES', 'partera_sabedor', 'Acompañamiento de partera, sabedor o médico tradicional en los procesos de salud enfermedad', 5, false, false, NULL),
  ('SABERES_ANCESTRALES', 'cuidado_entorno', 'Prácticas de cuidado con el entorno, con los alimentos u otros', 6, false, false, NULL),
  ('SABERES_ANCESTRALES', 'ninguna', 'Ninguna', 7, true, false, '{"excluyente":true}'::jsonb),
  ('DISCAPACIDAD', 'fisica', 'Física', 1, false, false, NULL),
  ('DISCAPACIDAD', 'auditiva', 'Auditiva', 2, false, false, NULL),
  ('DISCAPACIDAD', 'visual', 'Visual', 3, false, false, NULL),
  ('DISCAPACIDAD', 'sordoceguera', 'Sordoceguera', 4, false, false, NULL),
  ('DISCAPACIDAD', 'intelectual', 'Intelectual', 5, false, false, NULL),
  ('DISCAPACIDAD', 'psicosocial', 'Psicosocial (mental)', 6, false, false, NULL),
  ('DISCAPACIDAD', 'multiple', 'Múltiple', 7, false, false, NULL),
  ('DISCAPACIDAD', 'sin_discapacidad', 'Sin discapacidad', 8, true, false, '{"excluyente":true}'::jsonb),
  ('PRACTICAS_CUIDADO', 'alimentacion', 'Consume alimentos en cantidad y calidad suficiente todos los días', 1, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'actividad_fisica', 'Realiza actividad física, ejercicio o actividad deportiva', 2, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'higiene_oral', 'Higiene oral diaria (cepillado mínimo 2 veces al día)', 3, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'lavado_manos', 'Lavado de manos antes de consumir alimentos o después de entrar al baño, cambiar pañales, tener contacto con animales, retirar secreciones nasales, llegar de la calle, manipular sustancias químicas', 4, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'sueno', 'Duerme lo suficiente para estar con energía durante todo el día (entre 6 a 8 horas diarias)', 5, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'control_pantallas', 'Controla el tiempo de exposición a televisión, videojuegos y celular (menos de 2 horas al día)', 6, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'ocio', 'Realiza actividades en el tiempo libre o de ocio', 7, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'actividades_culturales', 'Participa en actividades culturales, sociales, alternativas o complementarias que aportan al cuidado de la salud', 8, false, false, NULL),
  ('PRACTICAS_CUIDADO', 'ninguna', 'Ninguna', 9, true, false, '{"excluyente":true}'::jsonb),
  ('ATENCIONES_RPMS', 'valoracion_integral_pyms', 'Valoración Integral para la PYMS', 1, false, false, '{"rangos":[[0,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'valoracion_salud_bucal', 'Valoración integral en salud bucal por profesional en odontología para la PYMS', 2, false, false, '{"rangos":[[0,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'lactancia_materna', 'Promoción y apoyo a lactancia materna', 3, false, false, '{"rangos":[[0,24]],"sexos":null,"gestante":true}'::jsonb),
  ('ATENCIONES_RPMS', 'aplicacion_fluor', 'Aplicación de flúor', 4, false, false, '{"rangos":[[12,215]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'profilaxis_placa', 'Profilaxis y remoción de placa bacteriana', 5, false, false, '{"rangos":[[24,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'vacunacion', 'Vacunación de acuerdo con el esquema', 6, false, false, '{"rangos":[[0,215],[720,null]],"sexos":null,"gestante":true}'::jsonb),
  ('ATENCIONES_RPMS', 'fortificacion_micronutrientes', 'Fortificación casera con micronutrientes en polvo', 7, false, false, '{"rangos":[[6,23]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'suplementacion_micronutrientes', 'Suplementación con micronutrientes', 8, false, false, '{"rangos":[[6,155]],"sexos":null,"gestante":true}'::jsonb),
  ('ATENCIONES_RPMS', 'desparasitacion', 'Desparasitación intestinal antihelmíntica', 9, false, false, '{"rangos":[[12,215]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_anemia', 'Tamizaje para anemia - Hemoglobina y hematocrito', 10, false, false, '{"rangos":[[6,71]],"sexos":null,"gestante":true,"mujerEdadFertil":true}'::jsonb),
  ('ATENCIONES_RPMS', 'asesoria_anticoncepcion', 'Asesoría en anticoncepción (planificación familiar)', 11, false, false, '{"rangos":[[156,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'suministro_anticonceptivos', 'Suministro de anticonceptivos', 12, false, false, '{"rangos":[[156,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_cardiovascular', 'Tamizaje de riesgo cardiovascular', 13, false, false, '{"rangos":[[216,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'prueba_treponemica', 'Prueba rápida treponémica', 14, false, false, '{"rangos":[[156,null]],"sexos":null,"gestante":true}'::jsonb),
  ('ATENCIONES_RPMS', 'prueba_vih', 'Prueba rápida y asesoría pre y postest VIH', 15, false, false, '{"rangos":[[156,null]],"sexos":null,"gestante":true}'::jsonb),
  ('ATENCIONES_RPMS', 'prueba_hepatitis', 'Prueba rápida para Hepatitis B (18 a 28 años) y C (22 a 28 años)', 16, false, false, '{"rangos":[[216,347]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'prueba_embarazo', 'Prueba de embarazo en caso de retraso menstrual u otros síntomas o signos de sospecha', 17, false, false, '{"rangos":[[120,null]],"sexos":["mujer","intersexual"]}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_cuello_uterino', 'Tamizaje para cáncer de cuello uterino (mujeres de 20 a 28 años)', 18, false, false, '{"rangos":[[240,347]],"sexos":["mujer","intersexual"]}'::jsonb),
  ('ATENCIONES_RPMS', 'colposcopia', 'Colposcopia y Biopsia cérvico uterina (mujeres)', 19, false, false, '{"rangos":[[240,null]],"sexos":["mujer","intersexual"]}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_mama', 'Tamizaje para cáncer de mama', 20, false, false, '{"rangos":[[480,null]],"sexos":["mujer","intersexual"]}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_prostata', 'Tamizaje para cáncer de próstata', 21, false, false, '{"rangos":[[600,null]],"sexos":["hombre","intersexual"]}'::jsonb),
  ('ATENCIONES_RPMS', 'tamizaje_colon', 'Tamizaje para cáncer de colon y recto', 22, false, false, '{"rangos":[[600,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'educacion_salud', 'Educación para la salud', 23, false, false, '{"rangos":[[0,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_RPMS', 'ninguna', 'Ninguna', 24, true, false, '{"excluyente":true,"rangos":[[0,null]],"sexos":null}'::jsonb),
  ('ATENCIONES_MATERNO', 'preconcepcional', 'Atención para el cuidado preconcepcional', 1, false, false, NULL),
  ('ATENCIONES_MATERNO', 'ive', 'Interrupción Voluntaria del Embarazo -IVE-', 2, false, false, NULL),
  ('ATENCIONES_MATERNO', 'control_prenatal', 'Atención para el cuidado prenatal - Controles prenatales', 3, false, false, '{"esencial":true}'::jsonb),
  ('ATENCIONES_MATERNO', 'preparacion_maternidad', 'Preparación para la maternidad y paternidad', 4, false, false, NULL),
  ('ATENCIONES_MATERNO', 'puerperio', 'Atención del puerperio', 5, false, false, NULL),
  ('ATENCIONES_MATERNO', 'anticonceptivo_postparto', 'Provisión del método anticonceptivo post parto inmediato', 6, false, false, NULL),
  ('ATENCIONES_MATERNO', 'seguimiento_recien_nacido', 'Atención y seguimiento del recién nacido', 7, false, false, NULL),
  ('ATENCIONES_MATERNO', 'educacion_salud', 'Educación para la salud', 8, false, false, NULL),
  ('ATENCIONES_MATERNO', 'ninguna', 'Ninguna', 9, true, false, '{"excluyente":true}'::jsonb),
  ('BARRERAS_ACCESO', 'no_afiliado', 'No Afiliado', 1, false, false, '{"tipo":"aseguramiento","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'desconoce_derecho', 'Desconocimiento del derecho a las intervenciones', 2, false, false, '{"tipo":"informacion","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'desconoce_gratuidad', 'Desconocimiento que las intervenciones son gratuitas', 3, false, false, '{"tipo":"informacion","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'servicio_lejano', 'El servicio de salud está lejos del lugar de residencia', 4, false, false, '{"tipo":"geografica","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'sin_personal', 'No hay personal de salud en el centro de salud cercano', 5, false, false, '{"tipo":"geografica","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'tramites', 'Dificultades con trámites administrativos', 6, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'sin_agenda', '"No hay agenda" para esta atención', 7, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'no_sabe_solicitar', 'No sabe cómo solicitar la cita', 8, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'horarios_restringidos', 'Horarios de atención restringidos', 9, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'tiempos_espera', 'Largos tiempos de espera', 10, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'incomodidad_personal', 'No se siente cómodo(a) con el personal de salud', 11, false, false, '{"tipo":"cultural","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'no_puede_acudir', 'Persona enferma que no puede acudir al servicio', 12, false, false, '{"tipo":"dependencia","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'falta_tiempo_cuidador', 'Falta de tiempo del cuidador', 13, false, false, '{"tipo":"dependencia","prioridad":"prioritaria"}'::jsonb),
  ('BARRERAS_ACCESO', 'adecuacion_sociocultural', 'Falta de adecuación sociocultural del servicio', 14, false, false, '{"tipo":"cultural","prioridad":"regular"}'::jsonb),
  ('BARRERAS_ACCESO', 'ninguna', 'Ninguna', 15, true, false, '{"excluyente":true}'::jsonb),
  ('CONOCIMIENTO_DERECHO', 'derechos_deberes', 'Conoce los derechos y deberes en salud', 1, false, false, NULL),
  ('CONOCIMIENTO_DERECHO', 'informacion_atenciones', 'Tiene información sobre las atenciones y servicios de salud a los cuales tiene derecho (promoción, prevención, atención, rehabilitación)', 2, false, false, NULL),
  ('CONOCIMIENTO_DERECHO', 'lugares_servicios', 'Conoce los lugares donde pueden prestar los servicios de salud', 3, false, false, NULL),
  ('CONOCIMIENTO_DERECHO', 'resolver_dificultades', 'Conoce cómo resolver las dificultades que se le presentan para acceder a la atención en salud', 4, false, false, NULL),
  ('CLASIFICACION_ANTROPOMETRICA', 'obesidad', 'Obesidad', 1, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'sobrepeso', 'Sobrepeso', 2, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'riesgo_sobrepeso', 'Riesgo de Sobrepeso', 3, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'peso_adecuado', 'Peso Adecuado para la Talla o IMC adecuado para la edad', 4, false, false, '{"prioridad":null}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'riesgo_desnutricion', 'Riesgo de Desnutrición Aguda (en <5 años), o Riesgo de delgadez (en > de 4 años) o Bajo peso para la edad gestacional o Delgadez (en mayores de 17 años)', 5, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'desnutricion_moderada', 'Desnutrición Aguda Moderada', 6, false, false, '{"prioridad":"prioritaria"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'desnutricion_severa', 'Desnutrición Aguda Severa', 7, false, false, '{"prioridad":"inmediata"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'riesgo_delgadez', 'Riesgo de Delgadez', 8, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'delgadez', 'Delgadez', 9, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'bajo_peso_gestacional', 'Bajo Peso para la Edad Gestacional', 10, false, false, '{"prioridad":"prioritaria"}'::jsonb),
  ('CLASIFICACION_ANTROPOMETRICA', 'normal', 'Normal', 11, false, false, '{"prioridad":null}'::jsonb),
  ('SIGNOS_DESNUTRICION', 'cabeza', 'Cabeza', 1, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'cara', 'Cara', 2, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'piel', 'Piel', 3, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'torax_abdomen', 'Tórax y abdomen', 4, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'extremidades', 'Extremidades', 5, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'comportamiento', 'Comportamiento', 6, false, false, NULL),
  ('SIGNOS_DESNUTRICION', 'edema', 'Edema', 7, false, false, '{"severo":true}'::jsonb),
  ('SIGNOS_DESNUTRICION', 'ninguna', 'Ninguna', 8, true, false, '{"excluyente":true}'::jsonb),
  ('CLASIFICACION_TENSION', 'crisis', 'Crisis hipertensiva (sistólica más alta de 180 mm Hg y/o diastólica más alta de 120 mm Hg)', 1, false, false, '{"prioridad":"inmediata"}'::jsonb),
  ('CLASIFICACION_TENSION', 'nivel2', 'Alta - Hipertensión nivel 2 (sistólica 140 mm Hg o más alta o diastólica 90 mm Hg o más alta)', 2, false, false, '{"prioridad":"prioritaria"}'::jsonb),
  ('CLASIFICACION_TENSION', 'nivel1', 'Alta - Hipertensión nivel 1 (sistólica de 130 a 139 mm Hg o diastólica 80 a 89 mm Hg)', 3, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_TENSION', 'elevada', 'Elevada (sistólica de 120 a 129 mm Hg y diastólica menos de 80 mm Hg)', 4, false, false, '{"prioridad":"regular"}'::jsonb),
  ('CLASIFICACION_TENSION', 'normal', 'Normal (sistólica menos de 120 mm Hg y diastólica menos de 80 mm Hg)', 5, false, false, '{"prioridad":null}'::jsonb),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'obstetrica', 'Enfermedad obstétrica (trastornos hipertensivos, hemorragias, sepsis, diabetes gestacional, otra)', 1, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'cardiovascular', 'Enfermedades cardiovasculares (Hipertensión, enfermedad cardiaca)', 2, false, false, '{"cardiovascular":true}'::jsonb),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'diabetes', 'Diabetes', 3, false, false, '{"cardiovascular":true}'::jsonb),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'cancer', 'Cáncer', 4, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'epoc', 'EPOC', 5, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'raras_huerfanas', 'Enfermedades raras y huérfanas', 6, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'trastorno_mental', 'Trastorno mental', 7, false, false, '{"saludMental":true}'::jsonb),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'epilepsia', 'Epilepsia', 8, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'secuelas_lesiones', 'Secuelas de lesiones por causa externa (secuelas de accidentes, agresiones físicas e intento de suicidio)', 9, false, false, NULL),
  ('ENFERMEDADES_NO_TRANSMISIBLES', 'ninguna', 'Ninguna', 10, true, false, '{"excluyente":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'prevalentes_infancia', 'Enfermedades prevalentes de la infancia (Enfermedad Diarreica Aguda, Infección Respiratoria Aguda)', 1, false, false, '{"prioridad":"prioritaria","notifica":false,"infancia":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'tuberculosis', 'Tuberculosis', 2, false, false, '{"prioridad":"prioritaria","notifica":true,"contactos":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'lepra', 'Lepra', 3, false, false, '{"prioridad":"prioritaria","notifica":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'rabia', 'Rabia', 4, false, false, '{"prioridad":"inmediata","notifica":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'dengue', 'Dengue', 5, false, false, '{"prioridad":"prioritaria","notifica":true,"vectorial":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'chikunguya', 'Chikunguya', 6, false, false, '{"prioridad":"prioritaria","notifica":true,"vectorial":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'zika', 'Zika', 7, false, false, '{"prioridad":"prioritaria","notifica":true,"vectorial":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'chagas', 'Chagas', 8, false, false, '{"prioridad":"prioritaria","notifica":true,"vectorial":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'leishmaniasis_visceral', 'Leishmaniasis visceral', 9, false, false, '{"prioridad":"inmediata","notifica":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'leishmaniasis_cutanea', 'Leishmaniasis Cutánea', 10, false, false, '{"prioridad":"prioritaria","notifica":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'tungiasis', 'Tungiasis', 11, false, false, '{"prioridad":"regular","notifica":false}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'eta', 'Enfermedades transmitidas por alimentos (Cólera, hepatitis A, parasitosis intestinal)', 12, false, false, '{"prioridad":"prioritaria","notifica":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'era', 'Enfermedad respiratoria aguda (ERA)', 13, false, false, '{"prioridad":"prioritaria","notifica":false,"infancia":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'eda', 'Enfermedad diarreica aguda (EDA)', 14, false, false, '{"prioridad":"prioritaria","notifica":false,"infancia":true}'::jsonb),
  ('CONDICIONES_TRANSMISIBLES', 'ninguna', 'Ninguna', 15, true, false, '{"excluyente":true}'::jsonb),
  ('ZONA_ENDEMICA', 'geohelmintiasis', 'Geohelmintiasis', 1, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZONA_ENDEMICA', 'teniasis', 'Teniasis / cisticercosis', 2, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZONA_ENDEMICA', 'tracoma', 'Tracoma', 3, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZONA_ENDEMICA', 'escabiosis', 'Escabiosis', 4, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZONA_ENDEMICA', 'pian', 'Pian', 5, false, false, '{"prioridad":"regular"}'::jsonb),
  ('ZONA_ENDEMICA', 'malaria', 'Malaria', 6, false, false, '{"prioridad":"prioritaria","notifica":true}'::jsonb),
  ('ZONA_ENDEMICA', 'ninguna', 'Ninguna', 7, true, false, '{"excluyente":true}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_afiliada', 'Persona no afiliada', 1, false, false, '{"tipo":"aseguramiento","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'servicio_lejano', 'El servicio de salud está lejos del lugar de residencia', 2, false, false, '{"tipo":"geografica","prioridad":"regular"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'tramites', 'Dificultades con trámites administrativos', 3, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'sin_agenda', '"No hay agenda" para esta atención', 4, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_sabe_solicitar', 'No sabe cómo solicitar la cita', 5, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_puede_copago', 'No puede pagar el copago', 6, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'horarios_restringidos', 'Horarios de atención restringidos', 7, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'tiempos_espera', 'Largos tiempos de espera', 8, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'incomodidad_personal', 'No se siente cómodo(a) con el personal de salud', 9, false, false, '{"tipo":"cultural","prioridad":"regular"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_puede_acudir', 'Persona enferma que no puede acudir al servicio', 10, false, false, '{"tipo":"dependencia","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_adherencia', 'No tiene adherencia al tratamiento', 11, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'sin_medicamentos', 'No hay disponibilidad de medicamentos en el centro de atención', 12, false, false, '{"tipo":"administrativa","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'falta_tiempo_cuidador', 'Falta de tiempo del cuidador', 13, false, false, '{"tipo":"dependencia","prioridad":"prioritaria"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'adecuacion_sociocultural', 'Falta de adecuación sociocultural del servicio', 14, false, false, '{"tipo":"cultural","prioridad":"regular"}'::jsonb),
  ('MOTIVO_NO_TRATAMIENTO', 'no_aplica', 'No aplica', 15, true, false, '{"excluyente":true}'::jsonb),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'inicio_convivencia', 'Inicio de la convivencia en pareja', 1, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'nuevo_integrante', 'Llegada de un nuevo integrante', 2, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'ingreso_estudiar', 'Ingreso a estudiar', 3, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'perdida_ano_escolar', 'Pérdida del año escolar', 4, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'embarazo_adolescente', 'Embarazo temprano o adolescente', 5, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'independencia_hogar', 'Independencia o salida del hogar paterno-materno', 6, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'separacion_pareja', 'Separación de pareja', 7, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'duelo', 'Duelo', 8, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'desempleo', 'Desempleo o pérdida abrupta del trabajo', 9, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'crisis_economica', 'Pérdidas o crisis económicas', 10, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'conflictos_familiares', 'Conflictos familiares', 11, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'abandono', 'Situación de abandono', 12, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'sin_redes', 'No identifica / No cuenta con redes de apoyo sociales protectoras', 13, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'estigma', 'Estigma y discriminación', 14, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'conflictos_orientacion', 'Conflictos relacionados con su orientación sexual', 15, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'trastorno_familiar', 'Trastorno de salud mental en algún integrante de la familia', 16, false, false, NULL),
  ('RIESGOS_SALUD_MENTAL_JOVEN', 'ninguna', 'Ninguna', 17, true, false, '{"excluyente":true}'::jsonb),
  ('SINTOMATOLOGIA_DEPRESIVA', 'tristeza', 'Se ha sentido triste todos los días durante la mayor parte del día', 1, false, false, NULL),
  ('SINTOMATOLOGIA_DEPRESIVA', 'anhedonia', 'Ha perdido el interés en actividades que antes disfrutaba', 2, false, false, NULL),
  ('SINTOMATOLOGIA_DEPRESIVA', 'inquietud', 'Se ha sentido inquieto(a) o nervioso(a) todos los días durante la mayor parte del día', 3, false, false, NULL),
  ('SINTOMATOLOGIA_DEPRESIVA', 'ninguno', 'Ninguno', 4, true, false, '{"excluyente":true}'::jsonb),
  ('IDEACION_SUICIDA', 'ha_pensado', 'Ha pensado en lastimarse o en no querer seguir viviendo', 1, false, false, '{"riesgo":true}'::jsonb),
  ('IDEACION_SUICIDA', 'ninguno', 'Ninguno', 2, true, false, '{"riesgo":false}'::jsonb),
  ('IDEACION_SUICIDA', 'no_aplica', 'No aplica', 3, true, false, '{"riesgo":false}'::jsonb),
  ('TIPO_RESPUESTA', 'en_sitio', 'En sitio', 1, false, false, NULL),
  ('TIPO_RESPUESTA', 'derivada', 'Derivada', 2, false, false, NULL),
  ('ESTADO_SEGUIMIENTO', 'C', 'C: Cumple', 1, false, false, '{"cumple":true}'::jsonb),
  ('ESTADO_SEGUIMIENTO', 'CP', 'CP: Cumple Parcial', 2, false, false, '{"cumple":false}'::jsonb),
  ('ESTADO_SEGUIMIENTO', 'NC', 'NC: No cumple', 3, false, false, '{"cumple":false}'::jsonb),
  ('TIPO_ID_EJECUTOR', 'CC', 'CC. Cédula de Ciudadanía', 1, false, false, NULL),
  ('TIPO_ID_EJECUTOR', 'CD', 'CD. Carné Diplomático', 2, false, false, NULL),
  ('TIPO_ID_EJECUTOR', 'CE', 'CE. Cédula de Extranjería', 3, false, false, NULL),
  ('TIPO_ID_EJECUTOR', 'PT', 'PT. Permiso por Protección Temporal', 4, false, false, NULL)
ON CONFLICT (dominio_codigo, codigo) DO UPDATE
  SET etiqueta = EXCLUDED.etiqueta, orden = EXCLUDED.orden,
      es_excluyente = EXCLUDED.es_excluyente, exige_texto = EXCLUDED.exige_texto;

/* --- Tipificación de barreras de acceso (RN-210) ------------------------- */
INSERT INTO cat.dominio (codigo, nombre, item, regla, multiple) VALUES
  ('TIPO_BARRERA', 'tipo de barrera de acceso', NULL, 'RN-210', false)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cat.opcion (dominio_codigo, codigo, etiqueta, orden, metadata) VALUES
  ('TIPO_BARRERA','administrativa','Administrativa — gestión ante EAPB',1,'{"prioridad":"prioritaria"}'),
  ('TIPO_BARRERA','geografica','Geográfica — extramural o telesalud',2,'{"prioridad":"regular"}'),
  ('TIPO_BARRERA','informacion','De información — educación en salud',3,'{"prioridad":"regular"}'),
  ('TIPO_BARRERA','cultural','Cultural o de trato — enfoque diferencial',4,'{"prioridad":"regular"}'),
  ('TIPO_BARRERA','cuidador','Del cuidador o dependencia — atención domiciliaria',5,'{"prioridad":"prioritaria"}'),
  ('TIPO_BARRERA','aseguramiento','De aseguramiento — conforme a RN-209',6,'{"prioridad":"prioritaria"}')
ON CONFLICT (dominio_codigo, codigo) DO NOTHING;

COMMIT;
