/* =========================================================================
   Diccionario de variables del archivo plano APS124CCFP (SI-APS)
   -------------------------------------------------------------------------
   GENERADO por bd/sispro/gen_diccionario.js desde las tablas resumen del
   anexo técnico (bd/sispro/anexo_APS124CCFP_v7.md, versión 7, junio 2026).
   No se edita a mano: se corrige el anexo o el generador y se regenera.

   tipo: N numérico entero · A alfanumérico · D decimal · F fecha · T texto
   ========================================================================= */

'use strict';

const TIPO_1 = [
  { n: 0, nombre: "Tipo de registro", max: 1, tipo: 'N', requerido: true },
  { n: 1, nombre: "Tipo de Identificación de la entidad que reporta", max: 2, tipo: 'A', requerido: true },
  { n: 2, nombre: "Número de identificación de la entidad que reporta", max: 12, tipo: 'N', requerido: true },
  { n: 3, nombre: "Fecha inicial del período de la información reportada", max: 10, tipo: 'F', requerido: true },
  { n: 4, nombre: "Fecha final del período de la información reportada", max: 10, tipo: 'F', requerido: true },
  { n: 5, nombre: "Número total de registros de detalle contenidos en el archivo", max: 10, tipo: 'N', requerido: true }
];

const TIPO_2 = [
  { n: 0, nombre: "Tipo de registro", max: 1, tipo: 'N', requerido: true },
  { n: 1, nombre: "Consecutivo de registro", max: 10, tipo: 'N', requerido: true },
  { n: 2, nombre: "Consentimiento informado", max: 1, tipo: 'N', requerido: true },
  { n: 3, nombre: "Departamento vivienda", max: 2, tipo: 'A', requerido: true },
  { n: 4, nombre: "Subregión vivienda", max: 3, tipo: 'A', requerido: true },
  { n: 5, nombre: "Municipio vivienda", max: 5, tipo: 'A', requerido: true },
  { n: 6, nombre: "Territorio vivienda", max: 3, tipo: 'A', requerido: true },
  { n: 7, nombre: "Microterritorio vivienda", max: 4, tipo: 'A', requerido: true },
  { n: 8, nombre: "Tipo de ubicación vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 9, nombre: "Nombre tipo de ubicación vivienda", max: 200, tipo: 'T', requerido: true },
  { n: 10, nombre: "Área de ubicación vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 11, nombre: "Punto de referencia de la ubicación", max: 200, tipo: 'T', requerido: true },
  { n: 12, nombre: "Geopunto longitud", max: 10, tipo: 'D', requerido: true },
  { n: 13, nombre: "Geopunto latitud", max: 10, tipo: 'D', requerido: true },
  { n: 14, nombre: "Dirección vivienda", max: 200, tipo: 'T', requerido: true },
  { n: 15, nombre: "Teléfono", max: 10, tipo: 'N', requerido: false },
  { n: 16, nombre: "Estrato socioeconómico vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 17, nombre: "No. Familias vivienda", max: 2, tipo: 'N', requerido: true },
  { n: 18, nombre: "No. Personas vivienda", max: 3, tipo: 'N', requerido: true },
  { n: 19, nombre: "No. Habitaciones vivienda", max: 2, tipo: 'N', requerido: true },
  { n: 20, nombre: "No. Personas por habitación", max: 3, tipo: 'N', requerido: true },
  { n: 21, nombre: "Hacinamiento", max: 1, tipo: 'N', requerido: true },
  { n: 22, nombre: "Elementos para dormir en la vivienda", max: 2, tipo: 'N', requerido: true },
  { n: 23, nombre: "Tipo de situación (situación que requiere atención inmediata y prioritaria).", max: 5, tipo: 'A', requerido: true },
  { n: 24, nombre: "Observaciones situación", max: 200, tipo: 'T', requerido: true },
  { n: 25, nombre: "Número de identificación del Equipo Básico de Salud (EBS)", max: 10, tipo: 'A', requerido: true },
  { n: 26, nombre: "NIT del prestador primario / Organismo de adscripción del EBS.", max: 9, tipo: 'N', requerido: true },
  { n: 27, nombre: "Tipo de identificación del responsable de la visita", max: 2, tipo: 'A', requerido: true },
  { n: 28, nombre: "Número de identificación del responsable de la visita", max: 20, tipo: 'A', requerido: true },
  { n: 29, nombre: "Perfil de quien realiza la visita", max: 200, tipo: 'T', requerido: true },
  { n: 30, nombre: "Fecha diligenciamiento de la ficha", max: 10, tipo: 'F', requerido: true },
  { n: 31, nombre: "Tipo de vivienda", max: 2, tipo: 'N', requerido: true },
  { n: 32, nombre: "Escenarios de riesgo de accidente en la vivienda", max: 20, tipo: 'A', requerido: true },
  { n: 33, nombre: "Cerca de la vivienda hay", max: 56, tipo: 'A', requerido: true },
  { n: 34, nombre: "Ambientes de la vivienda con luz natural", max: 11, tipo: 'N', requerido: true },
  { n: 35, nombre: "Ambientes de la vivienda con ventilación natural o artificial", max: 11, tipo: 'N', requerido: true },
  { n: 36, nombre: "Elementos en la vivienda", max: 5, tipo: 'N', requerido: true },
  { n: 37, nombre: "Alumbrado predominante en la vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 38, nombre: "Acceso a la vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 39, nombre: "Otros accesos a la vivienda", max: 200, tipo: 'T', requerido: false },
  { n: 40, nombre: "Material predominante techo", max: 2, tipo: 'N', requerido: true },
  { n: 41, nombre: "Cocina separada de la vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 42, nombre: "Baño separado de la vivienda", max: 1, tipo: 'N', requerido: true },
  { n: 43, nombre: "Dormitorios separados", max: 1, tipo: 'N', requerido: true },
  { n: 44, nombre: "Medio de transporte habitual", max: 20, tipo: 'N', requerido: true },
  { n: 45, nombre: "Otros medios de transporte", max: 200, tipo: 'T', requerido: false },
  { n: 46, nombre: "Seguridad en el desplazamiento", max: 13, tipo: 'A', requerido: true },
  { n: 47, nombre: "Otros elementos de seguridad", max: 200, tipo: 'T', requerido: false },
  { n: 48, nombre: "Desplazamiento mayor a 30 minutos", max: 11, tipo: 'N', requerido: true },
  { n: 49, nombre: "Otros factores de tiempo de desplazamiento", max: 200, tipo: 'T', requerido: false },
  { n: 50, nombre: "¿Se realiza actividad económica?", max: 1, tipo: 'N', requerido: true },
  { n: 51, nombre: "¿Área de trabajo independiente?", max: 1, tipo: 'N', requerido: true },
  { n: 52, nombre: "¿Familiar afectado por actividad económica?", max: 1, tipo: 'N', requerido: true },
  { n: 53, nombre: "Fuente principal de agua para consumo humano", max: 32, tipo: 'A', requerido: true },
  { n: 54, nombre: "Horas con suministro de agua", max: 1, tipo: 'N', requerido: true },
  { n: 55, nombre: "Tanque de almacenamiento de agua", max: 1, tipo: 'N', requerido: true },
  { n: 56, nombre: "Frecuencia de limpieza de tanque", max: 1, tipo: 'N', requerido: true },
  { n: 57, nombre: "Distancia entre tanque y el pozo o alcantarillado", max: 1, tipo: 'N', requerido: true },
  { n: 58, nombre: "Sistema de disposición de excretas", max: 13, tipo: 'A', requerido: true },
  { n: 59, nombre: "Sistema de disposición de aguas residuales domésticas", max: 11, tipo: 'A', requerido: true },
  { n: 60, nombre: "Almacenamiento de residuos solidos", max: 9, tipo: 'A', requerido: true },
  { n: 61, nombre: "Otros sistemas de almacenamiento de residuos solidos", max: 200, tipo: 'T', requerido: false },
  { n: 62, nombre: "Disposición final de los residuos sólidos ordinarios", max: 9, tipo: 'A', requerido: true },
  { n: 63, nombre: "¿Conoce prácticas de reducción y separación de residuos?", max: 1, tipo: 'N', requerido: true },
  { n: 64, nombre: "¿Realiza prácticas de reducción de residuos?", max: 1, tipo: 'N', requerido: true },
  { n: 65, nombre: "Como reduce la generación de residuos", max: 11, tipo: 'A', requerido: true },
  { n: 66, nombre: "Otros prácticas de reducción de generación residuos", max: 200, tipo: 'T', requerido: false },
  { n: 67, nombre: "¿Realiza prácticas de aprovechamiento de residuos?", max: 1, tipo: 'N', requerido: true },
  { n: 68, nombre: "¿Qué otras prácticas de aprovechamiento de residuos?", max: 200, tipo: 'T', requerido: false },
  { n: 69, nombre: "¿Cómo realiza la disposición de residuos peligrosos?", max: 17, tipo: 'A', requerido: true },
  { n: 70, nombre: "Otras prácticas de disposición de residuos peligrosos", max: 200, tipo: 'T', requerido: false },
  { n: 71, nombre: "¿Realiza procesos de reducción y separación de residuos rurales?", max: 1, tipo: 'N', requerido: true },
  { n: 72, nombre: "¿Qué prácticas de aprovechamiento de residuos rurales realiza?", max: 9, tipo: 'N', requerido: true },
  { n: 73, nombre: "Otras prácticas de aprovechamiento de residuos rurales", max: 200, tipo: 'T', requerido: false },
  { n: 74, nombre: "¿Qué prácticas de separación de residuos rurales aplica?", max: 7, tipo: 'A', requerido: true },
  { n: 75, nombre: "Otras prácticas de aprovechamiento de residuos rurales", max: 200, tipo: 'T', requerido: false },
  { n: 76, nombre: "Limpieza de superficies", max: 1, tipo: 'N', requerido: true },
  { n: 77, nombre: "Otras prácticas de Limpieza de superficies", max: 200, tipo: 'T', requerido: false },
  { n: 78, nombre: "Fuente de energía para cocinar", max: 15, tipo: 'N', requerido: true },
  { n: 79, nombre: "Otras fuentes de energía para cocinar", max: 200, tipo: 'T', requerido: false },
  { n: 80, nombre: "Fuentes frecuentes de humo", max: 13, tipo: 'N', requerido: true },
  { n: 81, nombre: "Otras fuentes frecuentes de humo", max: 200, tipo: 'T', requerido: false },
  { n: 82, nombre: "Prácticas en la calidad del aire", max: 9, tipo: 'N', requerido: true },
  { n: 83, nombre: "Tipo de estufa", max: 7, tipo: 'N', requerido: true },
  { n: 84, nombre: "Criaderos que favorecen vectores de enfermedades", max: 1, tipo: 'N', requerido: false },
  { n: 85, nombre: "Vectores transmisores de enfermedades", max: 23, tipo: 'A', requerido: true },
  { n: 86, nombre: "Otros vectores transmisores de enfermedades", max: 200, tipo: 'T', requerido: false },
  { n: 87, nombre: "Medidas para el control de vectores transmisores de enfermedades", max: 32, tipo: 'A', requerido: true },
  { n: 88, nombre: "Otras medidas para el control de vectores transmisores de enfermedades", max: 200, tipo: 'T', requerido: false },
  { n: 89, nombre: "Animales ponzoñosos en el hogar", max: 13, tipo: 'A', requerido: true },
  { n: 90, nombre: "Otros animales ponzoñosos en el hogar", max: 200, tipo: 'T', requerido: false },
  { n: 91, nombre: "Medidas para reducir riesgo de animales ponzoñosos en el hogar", max: 20, tipo: 'A', requerido: true },
  { n: 92, nombre: "Animales que conviven con la familia", max: 26, tipo: 'A', requerido: true },
  { n: 93, nombre: "Cantidad de perros en el hogar", max: 3, tipo: 'N', requerido: true },
  { n: 94, nombre: "Cantidad de perros con vacuna antirrábica", max: 3, tipo: 'N', requerido: true },
  { n: 95, nombre: "Cantidad de gatos en el hogar", max: 3, tipo: 'N', requerido: true },
  { n: 96, nombre: "Cantidad de gatos con vacuna antirrábica", max: 3, tipo: 'N', requerido: true },
  { n: 97, nombre: "Finalidad de tenencia de los animales en el hogar", max: 7, tipo: 'A', requerido: true },
  { n: 98, nombre: "Confinamiento de los animales", max: 5, tipo: 'A', requerido: true },
  { n: 99, nombre: "¿Se desparasita a los animales domésticos?", max: 1, tipo: 'N', requerido: true },
  { n: 100, nombre: "Instalaciones seguras", max: 1, tipo: 'N', requerido: true },
  { n: 101, nombre: "Excretas de los animales se recogen y disponen adecuadamente", max: 1, tipo: 'N', requerido: true },
  { n: 102, nombre: "Vivienda con barreras para evitar contacto directo con los animales", max: 1, tipo: 'N', requerido: true },
  { n: 103, nombre: "Medidas para el control de vectores transmisoras de enfermedades", max: 1, tipo: 'N', requerido: true },
  { n: 104, nombre: "Lugar donde adquiere productos químicos", max: 1, tipo: 'N', requerido: true },
  { n: 105, nombre: "Disposición final de residuos químicos", max: 15, tipo: 'A', requerido: true },
  { n: 106, nombre: "Otras prácticas de disposición final de residuos químicos", max: 200, tipo: 'T', requerido: false },
  { n: 107, nombre: "Seguimiento de instrucciones para manejo y almacenamiento de quimicos.", max: 1, tipo: 'N', requerido: true },
  { n: 108, nombre: "Productos en envase original y lugar asignado", max: 1, tipo: 'N', requerido: true },
  { n: 109, nombre: "Protección y ventilación al limpiar", max: 1, tipo: 'N', requerido: true },
  { n: 110, nombre: "No. Personas", max: 2, tipo: 'N', requerido: true },
  { n: 111, nombre: "Alias Familia", max: 200, tipo: 'T', requerido: true },
  { n: 112, nombre: "Tipo de familia", max: 1, tipo: 'N', requerido: true },
  { n: 113, nombre: "Apgar Familiar", max: 1, tipo: 'N', requerido: true },
  { n: 114, nombre: "¿Cuidador principal?", max: 1, tipo: 'N', requerido: true },
  { n: 115, nombre: "Escala ZARIT", max: 3, tipo: 'N', requerido: true },
  { n: 116, nombre: "Familia con situaciones que generan riesgo para la salud física o mental", max: 50, tipo: 'A', requerido: true },
  { n: 117, nombre: "Prácticas que favorecen los vínculos familiares.", max: 11, tipo: 'A', requerido: true },
  { n: 118, nombre: "Redes de apoyo social", max: 1, tipo: 'N', requerido: true },
  { n: 119, nombre: "Prácticas para el cuidado de la salud y protección en el hogar.", max: 15, tipo: 'A', requerido: true },
  { n: 120, nombre: "Medidas ante enfermedades respiratorias", max: 1, tipo: 'N', requerido: true },
  { n: 121, nombre: "Otras medidas ante enfermedades respiratorias", max: 200, tipo: 'T', requerido: false },
  { n: 122, nombre: "Implementos de higiene personal compartidos", max: 1, tipo: 'N', requerido: true },
  { n: 123, nombre: "Número de identificación de la vivienda", max: 26, tipo: 'A', requerido: true },
  { n: 124, nombre: "Número de identificación de la familia.", max: 31, tipo: 'A', requerido: true }
];

const TIPO_3 = [
  { n: 0, nombre: "Tipo de registro", max: 1, tipo: 'N', requerido: true },
  { n: 1, nombre: "Consecutivo de registro", max: 10, tipo: 'N', requerido: true },
  { n: 2, nombre: "Primer Nombre", max: 60, tipo: 'T', requerido: true },
  { n: 3, nombre: "Segundo Nombre", max: 60, tipo: 'T', requerido: false },
  { n: 4, nombre: "Primer Apellido", max: 60, tipo: 'T', requerido: true },
  { n: 5, nombre: "Segundo Apellido", max: 60, tipo: 'T', requerido: false },
  { n: 6, nombre: "Tipo de identificación", max: 2, tipo: 'A', requerido: true },
  { n: 7, nombre: "Número de identificación", max: 20, tipo: 'A', requerido: true },
  { n: 8, nombre: "Fecha de Nacimiento", max: 10, tipo: 'F', requerido: true },
  { n: 9, nombre: "País de origen", max: 3, tipo: 'N', requerido: true },
  { n: 10, nombre: "Estatus Migratorio", max: 1, tipo: 'N', requerido: true },
  { n: 11, nombre: "Sexo al nacer", max: 1, tipo: 'N', requerido: true },
  { n: 12, nombre: "Género", max: 1, tipo: 'N', requerido: true },
  { n: 13, nombre: "¿Genero qué se identifica la persona?", max: 1, tipo: 'N', requerido: true },
  { n: 14, nombre: "¿Cuál es la orientación sexual?", max: 1, tipo: 'N', requerido: true },
  { n: 15, nombre: "Teléfono principal", max: 20, tipo: 'N', requerido: false },
  { n: 16, nombre: "Teléfono secundario", max: 20, tipo: 'N', requerido: false },
  { n: 17, nombre: "Rol dentro de la familia", max: 1, tipo: 'N', requerido: true },
  { n: 18, nombre: "Ocupación", max: 4, tipo: 'N', requerido: true },
  { n: 19, nombre: "Nivel Educativo", max: 2, tipo: 'N', requerido: true },
  { n: 20, nombre: "Régimen de afiliación", max: 1, tipo: 'N', requerido: true },
  { n: 21, nombre: "EAPB", max: 8, tipo: 'N', requerido: false },
  { n: 22, nombre: "¿Es sujeto de protección constitucional o tiene alguna condición especial?", max: 32, tipo: 'A', requerido: true },
  { n: 23, nombre: "Modalidad Violencia", max: 200, tipo: 'T', requerido: false },
  { n: 24, nombre: "Pertenencia étnica", max: 2, tipo: 'A', requerido: true },
  { n: 25, nombre: "¿A qué pueblo o comunidad étnica pertenece?", max: 60, tipo: 'T', requerido: false },
  { n: 26, nombre: "Prácticas de cuidado de la salud desde sus saberes ancestrales/tradicionales", max: 11, tipo: 'A', requerido: true },
  { n: 27, nombre: "Prácticas para el ejercicio y exigibilidad del derecho a la salud", max: 7, tipo: 'A', requerido: true },
  { n: 28, nombre: "¿Realiza rutinariamente las siguientes prácticas para el cuidado y salud?", max: 15, tipo: 'A', requerido: true },
  { n: 29, nombre: "Atenciones pendientes de promoción y mantenimiento", max: 81, tipo: 'A', requerido: true },
  { n: 30, nombre: "¿Es persona con discapacidad?", max: 13, tipo: 'A', requerido: true },
  { n: 31, nombre: "Tiene certificación y registro de discapacidad (RLCPD)", max: 1, tipo: 'N', requerido: true },
  { n: 32, nombre: "Intención reproductiva a corto plazo", max: 1, tipo: 'N', requerido: true },
  { n: 33, nombre: "Gestación actual confirmada", max: 1, tipo: 'N', requerido: true },
  { n: 34, nombre: "Atenciones pendientes de la ruta materno perinatal", max: 15, tipo: 'A', requerido: true },
  { n: 35, nombre: "Motivo por el cual no ha recibido las atenciones de promoción y mantenimiento de la salud o materno perinatal", max: 32, tipo: 'A', requerido: true },
  { n: 36, nombre: "Menores de 6 meses ¿Recibe lactancia exclusiva?", max: 1, tipo: 'N', requerido: true },
  { n: 37, nombre: "Peso (en kilogramos)", max: 5, tipo: 'D', requerido: true },
  { n: 38, nombre: "Talla (en centímetros)", max: 5, tipo: 'D', requerido: true },
  { n: 39, nombre: "Mayores de 5 años. Resultado del IMC", max: 4, tipo: 'D', requerido: true },
  { n: 40, nombre: "Mayores de 18 años. Circunferencia de cintura (cm)", max: 3, tipo: 'N', requerido: true },
  { n: 41, nombre: "Hay signos físicos de desnutrición aguda en niños/as de 3 meses a 5 años", max: 13, tipo: 'A', requerido: true },
  { n: 42, nombre: "Clasificación antropométrica del estado nutricional según Peso para la Talla (P/T) o IMC para la edad (tener en cuenta el grupo de edad o si es gestante)", max: 2, tipo: 'N', requerido: true },
  { n: 43, nombre: "¿Se lava las manos con agua y jabón?", max: 1, tipo: 'N', requerido: true },
  { n: 44, nombre: "Tensión arterial (Sistólica)", max: 3, tipo: 'N', requerido: true },
  { n: 45, nombre: "Tensión arterial (Diastólica)", max: 3, tipo: 'N', requerido: true },
  { n: 46, nombre: "Clasificación Tensión arterial", max: 1, tipo: 'N', requerido: true },
  { n: 47, nombre: "Alguien de la familia acudió a urgencias", max: 20, tipo: 'A', requerido: true },
  { n: 48, nombre: "Enfermedades sufridas en el último mes", max: 47, tipo: 'A', requerido: true },
  { n: 49, nombre: "Otras enfermedades sufridas en el último mes", max: 200, tipo: 'T', requerido: false },
  { n: 50, nombre: "Que hizo si la persona presento alguna afección el último mes", max: 1, tipo: 'N', requerido: true },
  { n: 51, nombre: "Otras enfermedades sufridas en el último mes", max: 200, tipo: 'T', requerido: false },
  { n: 52, nombre: "Mayores de 14 años. Durante las últimas dos semanas:", max: 5, tipo: 'A', requerido: true },
  { n: 53, nombre: "Para mayores de 14 años Como se ha sentido durante los últimos ocho días", max: 1, tipo: 'N', requerido: true },
  { n: 54, nombre: "Identifica riesgos para su salud física o mental", max: 50, tipo: 'A', requerido: true },
  { n: 55, nombre: "¿Situación de salud que limite sus actividades en la última semana?", max: 1, tipo: 'N', requerido: true },
  { n: 56, nombre: "Tiene diagnóstico", max: 1, tipo: 'N', requerido: true },
  { n: 57, nombre: "Tiene signos y síntomas compatibles sin diagnóstico", max: 1, tipo: 'N', requerido: true },
  { n: 58, nombre: "¿Presenta alguna condición de salud transmisible?", max: 32, tipo: 'A', requerido: true },
  { n: 59, nombre: "¿Tiene alguna enfermedad no transmisible?", max: 35, tipo: 'A', requerido: true },
  { n: 60, nombre: "¿Vive en zona endémica o presenta signos/síntomas?", max: 1, tipo: 'N', requerido: true },
  { n: 61, nombre: "Recibe atención y tratamiento actual", max: 1, tipo: 'N', requerido: true },
  { n: 62, nombre: "Motivo(s) por el (los) cuales(es) no ha recibido la atención.", max: 32, tipo: 'A', requerido: true },
  { n: 63, nombre: "Mayores de 14 años. ¿Consume alguna sustancia psicoactiva?", max: 1, tipo: 'N', requerido: true },
  { n: 64, nombre: "¿Consume tabaco?", max: 1, tipo: 'N', requerido: true },
  { n: 65, nombre: "Consumo máximo de cigarrillos diario", max: 2, tipo: 'N', requerido: false },
  { n: 66, nombre: "Años fumando", max: 2, tipo: 'N', requerido: false },
  { n: 67, nombre: "Puntaje riesgo ASSIST", max: 2, tipo: 'N', requerido: false },
  { n: 68, nombre: "Puntaje riesgo AUDIT", max: 2, tipo: 'N', requerido: false },
  { n: 69, nombre: "Puntaje riesgo Carlos CRAFFT", max: 2, tipo: 'N', requerido: false },
  { n: 70, nombre: "Fecha de la última menstruación (FUM)", max: 10, tipo: 'F', requerido: false },
  { n: 71, nombre: "Mujer en edad fértil", max: 1, tipo: 'N', requerido: false },
  { n: 72, nombre: "¿Se encuentra en embarazo?", max: 1, tipo: 'N', requerido: false },
  { n: 73, nombre: "¿Conoce los signos de alarma en el embarazo?", max: 1, tipo: 'N', requerido: false },
  { n: 74, nombre: "¿Conoce sobre Interrupción Voluntaria del Embarazo?", max: 1, tipo: 'N', requerido: false },
  { n: 75, nombre: "¿Inició atenciones prenatales?", max: 1, tipo: 'N', requerido: false },
  { n: 76, nombre: "¿Inició oportunamente la atención prenatal?", max: 1, tipo: 'N', requerido: false },
  { n: 77, nombre: "¿Tiene acceso a métodos anticonceptivos postparto?", max: 1, tipo: 'N', requerido: false },
  { n: 78, nombre: "Clasificación del riesgo gestacional", max: 1, tipo: 'N', requerido: false },
  { n: 79, nombre: "Clasificación del riesgo de preeclampsia", max: 1, tipo: 'N', requerido: false },
  { n: 80, nombre: "Número de atenciones prenatales", max: 2, tipo: 'N', requerido: false },
  { n: 81, nombre: "Atención para el cuidado preconcepcional", max: 1, tipo: 'N', requerido: false },
  { n: 82, nombre: "Atención para el cuidado prenatal – Controles prenatales", max: 1, tipo: 'N', requerido: false },
  { n: 83, nombre: "Preparación para la maternidad y paternidad", max: 2, tipo: 'N', requerido: false },
  { n: 84, nombre: "Fecha de atención del evento obstétrico", max: 10, tipo: 'F', requerido: false },
  { n: 85, nombre: "Atención del puerperio en las primeras 48 horas", max: 1, tipo: 'N', requerido: false },
  { n: 86, nombre: "Consulta de seguimiento al puerperio entre el tercer y quinto día post parto", max: 1, tipo: 'N', requerido: false },
  { n: 87, nombre: "Apoyo a la lactancia materna", max: 1, tipo: 'N', requerido: false },
  { n: 88, nombre: "Atención durante las primeras 24 horas de vida al recién nacido", max: 1, tipo: 'N', requerido: false },
  { n: 89, nombre: "Control entre 3 y 5 días recién nacido", max: 1, tipo: 'N', requerido: false },
  { n: 90, nombre: "Vacunación del recién nacido", max: 1, tipo: 'N', requerido: false },
  { n: 91, nombre: "Provisión del método anticonceptivo post parto inmediato", max: 2, tipo: 'N', requerido: false },
  { n: 92, nombre: "¿Cuenta con historial laboral?", max: 1, tipo: 'N', requerido: false },
  { n: 93, nombre: "Lugar de trabajo / Actividad específica (más reciente)", max: 200, tipo: 'T', requerido: false },
  { n: 94, nombre: "Nombre del Empleador", max: 200, tipo: 'T', requerido: false },
  { n: 95, nombre: "Periodo laboral (meses)", max: 2, tipo: 'N', requerido: false },
  { n: 96, nombre: "¿Cuenta con más empleos previos al actual?", max: 1, tipo: 'N', requerido: false },
  { n: 97, nombre: "Lugar de trabajo / Actividad específica", max: 200, tipo: 'T', requerido: false },
  { n: 98, nombre: "Nombre del Empleador", max: 200, tipo: 'T', requerido: false },
  { n: 99, nombre: "Periodo laboral (meses)", max: 2, tipo: 'N', requerido: false },
  { n: 100, nombre: "Lugar de trabajo / Actividad específica", max: 200, tipo: 'T', requerido: false },
  { n: 101, nombre: "Nombre del Empleador", max: 200, tipo: 'T', requerido: false },
  { n: 102, nombre: "Periodo laboral (meses)", max: 2, tipo: 'N', requerido: false },
  { n: 103, nombre: "En alguno de los trabajos desempeñados, ¿ha realizado alguna actividad que involucre asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 104, nombre: "En alguno de los trabajos desempeñados, ¿ha realizado alguna actividad relacionada con asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 105, nombre: "¿Cuáles son las actividades realizadas relacionada con asbesto?", max: 135, tipo: 'A', requerido: false },
  { n: 106, nombre: "¿Ha interactuado con materiales que tengan asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 107, nombre: "¿Cuáles son los materiales con los que interactuó con presencia de asbesto?", max: 5, tipo: 'A', requerido: false },
  { n: 108, nombre: "¿En qué modalidad de empleo se presentó mayormente la exposición?", max: 1, tipo: 'N', requerido: false },
  { n: 109, nombre: "En su hogar, ¿ha tenido alguna vez materiales que contengan asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 110, nombre: "¿Cuáles son los elementos del hogar que tiene presencia de asbesto?", max: 20, tipo: 'A', requerido: false },
  { n: 111, nombre: "¿En qué estado se encuentran los materiales que contienen asbesto en la vivienda?", max: 1, tipo: 'N', requerido: false },
  { n: 112, nombre: "En su hogar, ¿convive con alguien que haya trabajado con asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 113, nombre: "¿Ha realizado en su vivienda reparaciones con materiales que contengan asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 114, nombre: "¿Recuerda alguna actividad que haya implicado asbesto cerca de su hogar?", max: 1, tipo: 'N', requerido: false },
  { n: 115, nombre: "¿Cuáles son las actividades que implicaron presencia de asbesto cerca de su hogar?", max: 1, tipo: 'N', requerido: false },
  { n: 116, nombre: "¿Ha tenido familiares con enfermedades relacionadas con asbesto?", max: 1, tipo: 'N', requerido: false },
  { n: 117, nombre: "Número de Identificación de la Familia", max: 31, tipo: 'A', requerido: true },
  { n: 118, nombre: "Número de identificación único del integrante de la familia", max: 53, tipo: 'A', requerido: true }
];

module.exports = { TIPO_1, TIPO_2, TIPO_3 };
